### ISSUE TITLE
ok button should be selected in user-input dialog

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1046]
so that you can press enter when finished entering input

![image](https://cloud.githubusercontent.com/assets/28215/15371383/c6b575cc-1d00-11e6-9796-66c54bfd2131.png)

**Comment by H-Theking** [comment]
@qiemem How do I get to this dialogue?

**Comment by SethTisue** [comment]
with the `user-input` primitive

**Comment by H-Theking** [comment]
I did a minor edit and it turns out that all `UserDialog`s will be affected. Is it the required behaviour?: 
![userinput](https://cloud.githubusercontent.com/assets/6599060/17643410/462e5b26-6161-11e6-8b8c-a196887c466e.png)
![useroneof](https://cloud.githubusercontent.com/assets/6599060/17643411/588b38ac-6161-11e6-9a41-d7b96db48a84.png)
![yesorno](https://cloud.githubusercontent.com/assets/6599060/17643412/5cef6aa8-6161-11e6-9ba2-8295f2794401.png)

**Comment by qiemem** [comment]
That looks pretty ideal to me.

**Comment by mrerrormessage** [comment]
Closed by #1127
