### ISSUE TITLE
Tick counter now appears under speed slider in BehaviorSpace

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#1117]
The tick counter now appears under the speed slider in BehaviorSpace:

![screenshot from 2016-07-29 19-48-38](https://cloud.githubusercontent.com/assets/908754/17260016/ff19fe62-55c5-11e6-9421-4c5eefda11dc.png)

It is only updated when "Update plots and monitors" is checked, which is unexpected.

Should it be there at all? My guess is that it's an unintended side effect of #930, and likely to be more confusing than anything.

**Comment by mrerrormessage** [comment]
That's the same issue. There's one shared tick counter, so when it gets added to a new Swing pane it disappears from the other (not the best way to do things, but it will be resolved with this).

I agree that the tick counter shouldn't be there at all, which means it will stay in the main NetLogo tool bar.

**Comment by qiemem** [comment]
What's the fix for this going to look like? Is the speed slider going to still be there?

It would be nice if I could use `SpeedSliderPanel` (and `ViewUpdatePanel`) in LS, but I need them to be detached from the tick counter since I don't want the tick counter to be below the speed slider (for space reasons). Actually, the fact that these three depend on each other at all is pretty dumb: they should each be independently addable to the same panel.

As an aside, how dumb is it that UI content and structure is totally coupled with styling and layout in Swing/AWT? Makes me appreciate CSS, despite all its warts.

**Comment by Idloj** [comment]
> As an aside, how dumb is it that UI content and structure is totally coupled with styling and layout in Swing/AWT? Makes me appreciate CSS, despite all its warts.

I don't think it's totally coupled, I mean, the layout is determined with `setLayout` and the various layout managers (including custom ones), and there are all the `*UI` classes that actually paint the component, so the separation exists. (`JButton` is the content and structure, but `ButtonUI` is what actually paint the button, responds to events , etc.)

IMO, Swing is actually quite easy to extend with totally custom functionality (e.g., you can just extend `ButtonUI` and you've got another look (and feel) for buttons), and is well-designed for extensions/modifications with decoupling and so on (the `*UI` classes are a great example). You can see some nice custom swing stuff in "Swing Hacks".

**Comment by qiemem** [comment]
@Idloj I didn't mean to derail this issue; it was just a casual complaint. That said, being able to set the layout doesn't solve the problem since you add the layout constraints at the same time as adding components. Once a component is added, the constraints can never be changed, making it impossible to override the layout. Compare this to CSS/HTML, where you can just drop in a different CSS file to completely change layout. Fair point about the styling with `*UI` classes though; I had only been thinking about layout.

Anyway, all this is irrelevant to the issue at hand. I was just saying it would be nice to decouple the speed slider, tick label, and view update combo box.

**Comment by Idloj** [comment]
I wasn't talking about this issue, too, I was only talking about Swing itself. As for the layout, I'm quite sure you can change the constraints later (you'll need to call `revalidate` (or `repaint` or both, not sure) to update the view accordingly if you've already shown the component). You're totally right that CSS is nicer (much more than an imperative set of calls to `set...`), but Swing isn't that bad at all.

**Comment by SethTisue** [comment]
I think it was an error, both conceptually and pragmatically, to move the tick counter out of the model interface and into the toolbar. it means the ticks won't show up in export-interface and movie-grab-interface, which is a disaster. The tick counter is properly part of the model UI.
