### ISSUE TITLE
view2.5d not present in M9

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1120]
Not sure what happened.

**Comment by mrerrormessage** [comment]
I cut the release branch for M9 just before [this commit](https://github.com/NetLogo/NetLogo/commit/2d3a9be3744030dee5c2fd535761a0d5684750e9) was pushed. Due to a fix on Windows that took several days, M9 ended up "missing" code that had been merged in several days before its release

 To clarify: the primary reason behind the build time for M9 was that a new version of the JDK was released which fixed (or should have fixed) a bug for the `vid` extension on Ubuntu 16. Other changes were pulled in as well, but M9 would have been built a week later had the java update come out a week later.
