### ISSUE TITLE
Indenter makes model indentation/navigation slow

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#1287]
This is especially true in large models. The indenter does a lot of backtracking to try to match components and a decent amount of string creation, all of which ends up being computationally expensive. This can be minimized to ensure a quicker experience for our users.

**Comment by Idloj** [comment]
duplicate of #1193

**Comment by qiemem** [comment]
@Idloj is right.

**Comment by qiemem** [comment]
To clarify, the reason this wasn't showing up on newlines and close brackets before was because they used a different path than tab-indenting. This resulted in inconsistencies in how indentation was applied, and thus I made them all use the same path in #1231. Thus, the slowness is all due to the same code now.
