### ISSUE TITLE
org.nlogo.api.ModelFormat.load should read ".nlogo" files using UTF-8 encoding

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#1294]
This issue is related to #353 

In my app using the Controlling API when I open the sample model Ants.nlogo all is fine.

But when I open BeeSmart Hive Finding.nlogo I get

java.nio.charset.UnmappableCharacterException: Input length = 1

When I looked at the character encodings I see that Ants.nlogo is ANSI while BeeSmart Hive Finding.nlogo is UTF-8.

Adding -Dfile.encoding=UTF-8 to the Java arguments fixes the problem. (This is documented at https://github.com/NetLogo/NetLogo/wiki/Controlling-API)

However one cannot distribute JARs with VM arguments and it is a pain to distribute scripts for different OSes that launch Java with the right arguments.

Why can't org.nlogo.api.ModelFormat.load explicitly set the encoding to UTF8?  Given that the NetLogo executable does so and it is recommended for controlling apps why put the burden on those launching controlling apps?

**Comment by mrerrormessage** [comment]
Various sources say that it is never a good idea to set `file.encoding` after application startup in Java, since many core Java classes cache the value of `file.encoding` on startup ([this writeup](http://www.philvarner.com/2009/10/24/unicode-in-java-default-charset-part-4/) was the most thorough I could find, but the general advice was echoed in a number of places).

This issue does raise a good point (I'm adjusting the title slightly to make it clearer) that whenever we read a ".nlogo" file from the file system we should specify a character encoding if possible. This wouldn't necessarily mean that every file NetLogo reads and writes would be UTF-8 encoded (for instance, the `file-` prims will still use the system default) but it would provide a consistent standard for model opening.

**Comment by mrerrormessage** [comment]
Note for anyone looking to fix this. The relevant spots to look are:

* [NLogoFormat](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-core/src/main/fileformat/NLogoFormat.scala#L37-L38)
* [App.loadDefaultModel](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/src/main/app/App.scala#L576)
* [App.reload](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/src/main/app/App.scala#L705) (note that FileIO.file2String doesn't set encoding)
* [App.magicOpen](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/src/main/app/App.scala#L722)

A variant of `FileIO.file2String` should probably be added which takes an encoding parameter (or perhaps a [`scala.Codec`](http://www.scala-lang.org/api/current/scala/io/Codec.html)) and uses that to read in the file.

**Comment by ToonTalk** [comment]
Good. I see too that Java caches the default so setting that is a bad idea. But as you say specifying the encoding when reading and writing would address this problem.
