### ISSUE TITLE
indent

### ISSUE THREAD

**Issue by cbradyatinquire** [NetLogo/NetLogo#1338]

**Comment by cbradyatinquire** [comment]
sorry for the duplicate --> opening the bug was a user-fail on github :) - i thought i was searching the open bugs for "indent" :)

**Comment by mrerrormessage** [comment]
Thanks for reporting! We've actually done a lot of work on the indenter recently. There were some behavioral changes to the indenter in NetLogo 6 and a we've overhauled it again since then for performance reasons. 

Entering the code you have above in NetLogo 6, I don't see the auto-indentation causing the behavior shown in the screenshot. Do you remember the order you entered the code in that triggered this? I can find ways to enter the code which indent `maybe-produce-trash` 0, 2, and 4 spaces, but none that indent it 3 spaces (as it appears in your screenshot).

**Comment by mrerrormessage** [comment]
I believe that #1441 has captured the most important features of this bug and has a better description on what the fix for it needs to be. I'm closing this one.
