### ISSUE TITLE
Infotab - (un-)ordered lists

### ISSUE THREAD

**Issue by daimpi** [NetLogo/NetLogo#1346]
I've encountered some confusions around (un-) ordered lists in the documentation and the use of the lists:

1. the documentation seemingly gives two examples of ordered lists in the code section, but the output shown below is for unordered lists: https://ccl.northwestern.edu/netlogo/docs/infotab.html#ordered_lists

2. The link to the section of unordered lists doesn't seem to work (probably b/c the section doesn't exist) and instead throws back to the top of the infotab section : https://ccl.northwestern.edu/netlogo/docs/infotab.html#unordered_lists
 
3. When using lists in the infotab of NetLogo I figured that in order to go one list level deeper the indentation had to be increased by 4 spaces instead of two spaces as indicated in the documentation. Also: the first level seemingly doesn't need any indentation. So while it's true that the 2nd level needs 4 spaces indentation the first one seemingly can have two or none while the third would need 8.

4. The subitems in in ordered lists receive more indentation in the output than unordered lists. Level two in an ordered list seems to be corresponding to level three in an unordered list wrt indentation of the output.

5. The subitems in unordered lists don't receive different symbols for different levels anymore (which they did in 5.3.1).

Here is an example for code in the infotab: 

```
* hi

  * hi
    * hi
    * hi

  1. bla
    1. blu
    2. na
        1. hu

  * a
    * b
        * c

```

5.3.1: 
![grafik](https://cloud.githubusercontent.com/assets/22129968/23356964/1bf48e54-fcdc-11e6-90ff-9cf23d473654.png)

6.0:
![grafik](https://cloud.githubusercontent.com/assets/22129968/23356987/315c4660-fcdc-11e6-9c28-ad317e00b33e.png)

**Comment by mrerrormessage** [comment]
Thanks for reporting:

Issues (1) and (2) will be addressed in https://github.com/NetLogo/models/issues/341 . We have a separate repository for our models library, so I've filed the bug there. 

Issue (3) and (4) are legitimate, but we're limited by Pegdown, our Markdown parsing library. Unfortunately, Pegdown is no longer maintained and has a number of tickets piling up (no doubt for things like inconsistent list indentation). I've created https://github.com/NetLogo/NetLogo/issues/1347 to address the transition issue.

Issue (5) changed as part of https://github.com/NetLogo/NetLogo/pull/1152 (fixing old bug https://github.com/NetLogo/NetLogo/issues/236). It was not noted in either ticket that different indentation levels received different bullet styles. While different styles can be helpful in visually parsing long unordered lists, the old bullets *were* way too large and ugly. It's probably possible for a CSS change to fix this problem, but I would want to roll any such changes into the fix for #1347 to prevent conflicts. I've made a note on #1347 to handle this. 

So I've split this ticket into https://github.com/NetLogo/models/issues/341 (to handle the info tab example, and by extension the NetLogo documentation page for the info tab) and #1347 to handle the behavioral issues with the info tab parser. I'm going to go ahead and close this issue. Please comment if there were any problems that were missed and we'll consider what to do going forward.
