### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mattsap** [NetLogo/NetLogo#1379]
Can anyone explain the documentation a little better for the benchmarking (see https://github.com/NetLogo/NetLogo/wiki/Benchmarking) ? For example, how do we install sbt and get it running if we don't have sbt installed already.

See: http://stackoverflow.com/questions/43265267/netlogo-benchmarking

**Comment by mattsap** [comment]
Per the stackoverflow thread, the ./sbt file is located in the root directory of this repository.

However, it's still unclear, which directory do we run the ./sbt command from.

 More particularly, I'm getting a Benchmarker class not found error. I'm not sure if these are related. =(

See:

> run-main org.nlogo.headless.HeadlessBenchmarker Fire
[warn] Credentials file /Users/tnj/.bintray/.credentials does not exist
[info] Running org.nlogo.headless.HeadlessBenchmarker Fire
[error] (run-main-1) java.lang.ClassNotFoundException: org.nlogo.headless.HeadlessBenchmarker
java.lang.ClassNotFoundException: org.nlogo.headless.HeadlessBenchmarker
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[trace] Stack trace suppressed: run last root/compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last root/compile:runMain for the full output.
[error] (root/compile:runMain) Nonzero exit code: 1
[error] Total time: 0 s, completed Apr 11, 2017 11:14:01 AM
> 


Any suggestions on what to do?

**Comment by mattsap** [comment]
The command in the documentation was incorrect. Need to run 

> headless/runMain org.nlogo.headless.HeadlessBenchmarker Bureaucrats

 instead of 

> run-main org.nlogo.headless.HeadlessBenchmarker Bureaucrats

**Comment by mrerrormessage** [comment]
Glad you were able to figure this out. Please note that running the benchmark through `sbt` is likely to result in innaccurate times as sbt has a substantial amount of overhead.

Instructions to fix the bintray warning can be found [here on the building page](https://github.com/NetLogo/NetLogo/wiki/Building#how-to-fix-bintray-warnings).

**Comment by mattsap** [comment]
If not run it through sbt, how would you run the benchmarks?

**Comment by mrerrormessage** [comment]
We run the benchmarks with `./bin/benches`. I noticed in your other issue that you were seeing high variability - that's probably due largely to running through sbt. Please note that the benchmarks are used primarily by the devel team when we're analyzing the performance of NetLogo. If you're trying to profile a given model to determine how to speed it up, we recommend using the [profiler extension](https://ccl.northwestern.edu/netlogo/docs/profiler.html), which can be run in both GUI and headless NetLogo.

**Comment by SethTisue** [comment]
on the subject of whether the benchmarks are suitable for use by model authors, see my remarks at http://stackoverflow.com/questions/43265267/netlogo-benchmarking#comment73718126_43308513

**Comment by SethTisue** [comment]
> We run the benchmarks with ./bin/benches.scala

is that what https://github.com/NetLogo/NetLogo/wiki/Benchmarking ought to be recommending?

**Comment by mattsap** [comment]
I would assume so...How would one run the whole suite though? I didn't see
that in the documentation.

**Comment by mrerrormessage** [comment]
@SethTisue , thanks for pointing that out - the page should be updated. To give a little background - I tried to move `./bin/benches.scala` inside `sbt` as a task and ran into several problems:

1. It didn't allow for easy control over JVM run options
2. Performance was measurably worse than running the model in `./bin/benches.scala`
3. Attaching an external performance monitor (like VisualVM was less useful)

It's possible that one or more of these considerations no longer applies or is possible to work around, but they formed the basis of the decision to keep a separate benchmark script (as opposed to moving the benchmarking functionality with sbt).

It's a good point that using the Headless Benchmarker is a much better way to test whole-model performance, and I didn't communicate that in my response.

@mattsap , simply running `./bin/benches.scala` will run the whole suite of NetLogo benchmarks. Note that since NetLogo 6 (approximately) you must have `SCALA_HOME` set when running `./bin/benches.scala` in order for it to execute properly.

**Comment by mattsap** [comment]
You guys are the greatest! Thanks for all the insight!

**Comment by SethTisue** [comment]
> I tried to move ./bin/benches.scala inside sbt as a task and ran into several problems

I think all 3 of your points would be addressed (or at least addressable) if the task forked a JVM instead of staying in sbt's JVM (http://www.scala-sbt.org/0.13/docs/Forking.html). but whatevs, having the script instead is fine, I don't see a strong reason to mess with it
