### ISSUE TITLE
Go in a while condition on ticks never stop

### ISSUE THREAD

**Issue by ElCep** [NetLogo/NetLogo#1422]
If you call a go proc in console like : `while [ticks <= 1001] [go]` ticks stop at 1001 but the model is still running.

**Comment by mrerrormessage** [comment]
Hi, can you attach a copy of the model you're seeing this behavior in (or send it to bugs@ccl.northwestern.edu with a reference to this issue).

Buttons in NetLogo run independently of the command center and each other, so we wouldn't expect that just because the command center stops running that other active buttons would become inactive. Many models make use of one forever button to let users "draw" on the model while using another forever button to actually run the model (the Life model from the library is a good example of this). Having the "draw" button stop just because the "go" button is being run (or vice-versa) doesn't really match with how NetLogo works in most cases.

**Comment by ElCep** [comment]
Hi,
It's done. I have send the model to bugs@ccl.northwestern.edu 
thnak you @mrerrormessage

**Comment by mrerrormessage** [comment]
This issue was addressed via response email. Closing.
