### ISSUE TITLE
A note of praise and appreciation for NetLogo

### ISSUE THREAD

**Issue by RussAbbott** [NetLogo/NetLogo#1590]
I'm using NetLogo in a modelling course this semester. Prior to this semester the last time I had used NetLogo was when it was at version 4. I'm very impressed with the changes and improvements made since then. Congratulations and thank you.

There are still a number of issues I would like to see addressed. But I'll leave those to other issue posts. 

For now I just want to say that @SethTisue and the other NetLogo developers/contributors have done an extraordinary job. I appreciate your work and accomplishments.

**Comment by SethTisue** [comment]
thank you!! that's wonderful to hear.

for the record... for anyone reading this... I was the lead maintainer of NetLogo from 2000 through 2014. (my involvement in recent years is just comments on GitHub and Stack Overflow, nothing more.)

the lead maintainer since 2014 has been Robert Grider (@mrerrormessage).

Uri Wilensky is the author of NetLogo and has always been in charge of the overall effort.

thanks again!

**Comment by mrerrormessage** [comment]
Agreed. Thank you!

Although I've been the lead maintainer of NetLogo since late 2015 (@frankduncan took over between Seth and myself) the entire CCL team regularly participates in important decisions, discussions, and code fixes.
