### ISSUE TITLE
A list bug 

### ISSUE THREAD

**Issue by YcZen** [NetLogo/NetLogo#1630]
breed [kids kid]
kids-own [toys]

to setup
  clear-all
  setup-kids
end

to setup-kids
  create-kids 1 [set toys list 2 3]  ;; assign a list to kids' own variable toys 
  ask kids [show [toys] of kids     ;; expect to show **[2,3]** but get **[[2,3]]** instead
            show item 0 ([toys] of kids)]  ;; expect to show **2** but get **[2,3]** instead.

**Comment by LaCuneta** [comment]
Hey @YcZen, thank you for the report.  I believe this is actually working as expected.  If you modify your example as follows it might be more clear what is happening:

```
to setup-kids
  create-kids 1 [set toys list 2 3]
  create-kids 1 [set toys list 4 5]
  create-kids 1 [set toys list 6 7]
  show [toys] of kids ; shows [[2 3] [4 5] [6 7]] in a random order
  show item 0 ([toys] of kids)] ; gets the toys of a single kid randomly
end
```

When you use `of` with an agent set, like `kids` in this case, it returns a list of the value for each member of the agent set.  See the [docs on `of` for more](https://ccl.northwestern.edu/netlogo/docs/dictionary.html#of).

What you might be looking for is something like this, using `of` with a single agent instead of an agent set:

```
to setup-kids
  create-kids 1 [set toys list 2 3]
  ask kids [ 
    show item 0 [toys] of self ; you will see 2
  ]
end
```

**Comment by YcZen** [comment]
@LaCuneta oh, I see. Thank you so much!

**Comment by LaCuneta** [comment]
I should point out that when you use `ask`, you enter the "context" of each agent, which means you don't need `of` at all to access a variable: 

```
ask kids [ ; enter the context of each `kid`, one at a time in random order
  show item 0 toys ; get the first item from the `toys` variable for the current `kid`
]

**Comment by YcZen** [comment]
I got it. kids with [id = 1] is also an agent list. thank you! @LaCuneta
