### ISSUE TITLE
How can i let Patches move and be more big? i have a problem that says i have an industry factory spills pollutants into a pond which is has water

### ISSUE THREAD

**Issue by Dawood220** [NetLogo/NetLogo#1743]

**Comment by LaCuneta** [comment]
Hello @Dawood220, thank you for your question and your interest in NetLogo.  This repository is for bugs with the NetLogo software itself, it's not a good place for general NetLogo programming questions.

For general programming questions with NetLogo, I recommend the NetLogo users group:  http://groups.google.com/d/forum/netlogo-users

Or the StackOverflow NetLogo tag, if you're familiar with the site:  https://stackoverflow.com/questions/tagged/netlogo

To answer your question, patches cannot move and you cannot change the size of a single patch or a few patches.  You can change size of all patches by editing the world properties (this is probably not what you want to do), see the `Patch-size` setting here:  https://ccl.northwestern.edu/netlogo/docs/interfacetab.html#the-2d-and-3d-views

My advice would be to use turtles with different breeds instead of patches to try to simulate what you're looking for, just give them a `shape` of `square` and set the `size` until it looks right.

I hope that helps.
