### ISSUE TITLE
Python NetLogo link

### ISSUE THREAD

**Issue by Tim-the-bean** [NetLogo/NetLogo#1757]
I have this error and (being new to Python) not sure what to do with it.

Python error output:
C:\Program Files\NetLogo 6.1.0\app\extensions\.bundled\py\pyext.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping

**Comment by LaCuneta** [comment]
@Tim-the-bean Thanks for the report!  

Since it's just a deprecation warning, you can ignore it, it's just saying there will be a problem if you were to use Python 3.8 with the NetLogo Python extension script.  We'll get the Python extension updated to remove that error in the future.  

Since this is related to the Python extension and NetLogo directly, I'm going to close this issue and open one in the Python-Extension repository.
