### ISSUE TITLE
Extension csv wrongly quotes negative numbers on the first column

### ISSUE THREAD

**Issue by mariopaolucci** [NetLogo/NetLogo#1764]
On my netlogo 6.04 on mac, this code:

`csv:to-file "myfile.csv" [ [ -0.7 0.7  ] [  0.7 -0.7 ] ]`

generates a file with unwanted quotation marks on the first column only, which makes it hard to process:

``` 
"-0.7",0.7
0.7,-0.7
```

I believe that the same happens if there is an exponential notation in the output on the first column.

**Comment by LaCuneta** [comment]
Mario, thanks for the report.

We have had this issue [reported before](https://github.com/NetLogo/CSV-Extension/issues/13) and as Bryan said in that issue, this is expected behavior for the CSV library we're using in the extension.  If you re-import the quoted negative number into NetLogo or open it in Excel or Numbers, the quoted negative value should get a "number type".  I'd expect other programming language CSV libraries to be able to handle it as well.

Let me know if you're trying to re-import the data into NetLogo using the CSV extension and it isn't coming back in as a number, that would definitely be an issue.
