### ISSUE TITLE
org.nlogo.nvm.RuntimePrimitiveException: Value must be one of: ["search-strategy-flock" "search-strategy-random" "search-strategy-symmetric"]

### ISSUE THREAD

**Issue by kenanxiao0118** [NetLogo/NetLogo#1765]
The chooser can work perfectly in NetLogo, but when I use pyNetLogo to set up the values of a global value (which is a chooser), it gives me the following error:

jpype._jexception.org.nlogo.nvm.RuntimePrimitiveExceptionPyRaisable: org.nlogo.nvm.RuntimePrimitiveException: Value must be one of: ["search-strategy-flock" "search-strategy-random" "search-strategy-symmetric"]

Any help would be useful, thanks

**Comment by LaCuneta** [comment]
To ask the obvious question, are you setting the value to one of the chooser possibilities?  No typos or possibly untrimmed whitespace?  I don't believe it would be case sensitive, but that would be worth checking, too.

If you can post your NetLogo model code and a snippet of your pyNetLogo code I might be able to help a bit more.  Off the top of my head, though, it would be an actual issue with the values being used by the model somehow.

**Comment by kenanxiao0118** [comment]
The chooser is called "global-search-strategy", and it can be chosen from three different global variables.

The NetLogo code works perfectly when running on NetLogo, however, when I set up the experiments using the Exploratory Modeling Workbench (EMA), which is developed based on PyNetLogo, jpype. And when I try to overwrite the default value of the global-search-strategy, it causes the above error. But if I use the default one (the last saved value of global-search-strategy) without overwriting, it works just fine.

I am not exactly sure which part of the NetLogo code causes the problem, since I set it up on EMA and it works just fine on pure NetLogo.

I am not exactly sure if it is the same type of issues #818 

Here is just a piece of the code for set-up:

![Screenshot 2019-07-17 10 35 16](https://user-images.githubusercontent.com/38436254/61389724-046bd700-a87f-11e9-9344-d6aed4d7a8f1.png)

Here is the part of the Python code:
![Screenshot 2019-07-17 10 39 44](https://user-images.githubusercontent.com/38436254/61389856-3d0bb080-a87f-11e9-9118-8b3fb012500e.png)

The following is the error from the Python: 

![Screenshot 2019-07-17 10 29 47](https://user-images.githubusercontent.com/38436254/61389903-59a7e880-a87f-11e9-8a2a-fb76eeee10a9.png)

Thank you so much for your reply!

**Comment by LaCuneta** [comment]
> The chooser is called "global-search-strategy", and it can be chosen from three different global variables.
> 

And what are the options for that chooser in the widget settings?

> The NetLogo code works perfectly when running on NetLogo, however, when I set up the experiments using the Exploratory Modeling Workbench (EMA), which is developed based on PyNetLogo, jpype. And when I try to overwrite the default value of the global-search-strategy, it causes the above error. But if I use the default one (the last saved value of global-search-strategy) without overwriting, it works just fine.
> 

I haven't used pyNetLogo much, and I've definitely not used EMA at all, so I'm a little out of my depth, but I'll try to think of a few more ideas.

> I am not exactly sure if it is the same type of issues #818
> 

Yeah, that issue is saying that NetLogo is throwing a hard error when you try to set a global variable that a chooser is referencing to a value that isn't in its list.  So if your chooser has options `[ "apples "oranges" ]` and has a variable named `fruit` and you do `set fruit "kiwi"` at the command center, you'll get that hard error.  Somehow in your model setup with pyNetLogo and EMA, it's trying to set that global variable to a value that isn't in the chooser list.  

So either the list of values you've set in the chooser doesn't match up with what you're using from pyNetLogo/EMA, or somehow pyNetLogo/EMA is sending a value to NetLogo that doesn't match what it's expecting.

One thing I notice looking at that code - you only set the values of those global variables up in `setup` - have you actually run `setup` from your pyNetLogo/EMA code at the time you do your `model.constants = [Constant("global-search-strategy", "search-strategy-flock")]` call?  If not, that `search-strategy-flock` global is going to be empty, and that may not be a valid value in the chooser list.

Another recommendation would be to try out a super simple model, maybe one with just a chooser and a couple simple options (like the `fruit` example above), then see if you're able to set the chooser from EMA to each of those values without error and output the contents of the chooser global at the end.  That should confirm it's not any kind of platform issue.

**Comment by kenanxiao0118** [comment]
I have tried a really simple model, using EMA to set up the chooser, it gives me another error.

![image](https://user-images.githubusercontent.com/38436254/61409017-fd58bf00-a8a6-11e9-9fb1-0891e46d41b1.png)

The model I use is really simple:

![image](https://user-images.githubusercontent.com/38436254/61409194-5294d080-a8a7-11e9-9d15-f0c6f45df76c.png)

The interface is the following:
![image](https://user-images.githubusercontent.com/38436254/61409263-76581680-a8a7-11e9-86a0-777a7b17825f.png)

Is it because of the case sensitive?

Thanks in advance!

**Comment by LaCuneta** [comment]
So that looks to me like EMA/pyNetLogo are passing the `kiwi` value as a raw text into NetLogo, as opposed to as a string.  Assuming your code looks like `model.constants = [Constant("fruit", "kiwi")]`, you could try changing it it `model.constants = [Constant("fruit", "\"kiwi\"")]`.  The added escaped quotes should give NetLogo a literal string value to use, instead of the raw text.  If that works, it lends support to the idea that the `setup` procedure isn't getting run in your original model before setting the global variables.

**Comment by kenanxiao0118** [comment]
When I changed it to the literal string, it worked！It is indeed setting the global variable first and then run **setup** procedure. 

Thank you so much for all the help!
