### ISSUE TITLE
Building Streets and Moving Agents along those Streets

### ISSUE THREAD

**Issue by CoffeeloverGER** [NetLogo/NetLogo#1781]
Hello everybody,

I'm fairly new to the entire topic of coding and also NetLogo. Nevertheless, I want to learn it and would like to have some advice from you. First, I want to build a very basic "city" consisting of some houses and some streets connecting those houses. In the next step, some cars should drive along the roads from one house to another.
Unfortunately, I don't know how to build that. Wherever I look for tutorials or guidelines, it is either too basic (create agents, to setup, adding the buttons,...) or way to complicated for me as a beginner. 
Do you have any advice on how to approach or learn NetLogo the easiest?

I appreciate every helpful input!
Thanks a lot!!

**Comment by LaCuneta** [comment]
Welcome and thanks for your interest in NetLogo!

This issues list is for reporting problems with NetLogo and tracking work on fixes.  It's not a great place to get help with creating models.  Fortunately, there are some better options:

- For general modeling questions, I recommend emailing [the NetLogo users Google Group](https://groups.google.com/forum/#!forum/netlogo-users), which has many people reading it who answer questions from beginners.  
- If you have specific technical questions on writing NetLogo code, [StackOverflow can be a good place to post a question with the `netlogo` tag](https://stackoverflow.com/questions/tagged/netlogo).

As for your specific question, firstly I'd recommend working all the way through [the basic NetLogo turtorial from our documentation](https://ccl.northwestern.edu/netlogo/docs/tutorial1.html).  Even if you think it's too simple, just going through the whole thing will get you used to writing NetLogo code.

Secondly, I'd recommend look at the traffic models that come with NetLogo, **Traffic Basic**, **Traffic 2 Lanes**, and **Traffic Grid**.  It would be a good exercise to take one of those models and see if you can make some small changes to them to get them more like what you're imagining for your model.

I'll be closing this issue here, but feel free to message the users group if you need further assistance.  Good luck!
