### ISSUE TITLE
NetLogoException(Compressed class space)

### ISSUE THREAD

**Issue by NedaMarvasti** [NetLogo/NetLogo#1793]
Hi, I am running 1000'000 simulation of netlogo and I got the following exception, any idea how to solve it?
NetLogoException(Compressed class space)

I should mention that running 100'000 simulations is totally fine with no such error.

Thanks.

**Comment by LaCuneta** [comment]
Neda, thanks for reporting this issue and sorry you ran into it.

We've seen a similar issue reported with the LevelSpace extension when it was hosting lots of child models.  The solution for it was to disable NetLogo's code generation, which makes extra classes for Java to track.  A second possibility is to disable compressed class pointers in Java, which is on by default.

If you're using the `netlogo-headless.sh` script that came with NetLogo to run your experiments you can pass `-Dorg.nlogo.noGenerator=true` to it to disable the generator.  To disable compressed class pointers, I believe you need to modify the script directly to add `-XX:-UseCompressedClassPointers` to the `JVM_OPTS` array.  If you've got your own custom script you'll have to modify it to pass those options to your Java runtime.

These settings may make your simulations run a bit more slowly, but the tradeoff should be that they'll successfully complete without error.

If you have more memory available on your system, you can also try increasing the amount of memory available to NetLogo by adjusting the `-Xmx` Java parameter in the script, too.  I'm not as sure that would help, but I believe the compressed class space is limited by the overall memory available to the app.

Let me know if these settings help, or if you still have issues.  Thanks.

**Comment by qiemem** [comment]
To clarify, are you setting the number of threads used by BehaviorSpace to 1,000,000? What sort of infrastructure are you running on? If this is for a cluster, I've often had better luck restricting the number of threads BehaviorSpace uses to the number of logical cores on a particular node, and then running a separate instance of NetLogo per node (by breaking up a single BehaviorSpace experiment into several smaller ones). But, obviously, this is highly dependent on your computing infrastructure. Because each of the independent threads are outputting to the same file, there is unfortunately quite a bit of synchronization that happens between threads, so it can be better to break jobs up into many NetLogo processes if they are are going to spread across multiple physical computers. This also sidesteps any memory considerations, so you can leave the generator on and use compressed class pointers.

**Comment by NedaMarvasti** [comment]
Hi,
Thanks for your responses. I think the problem is solved, simulations are not finished yet, but  at least there is no more out of memory error :).  It has been about 2 days that my simulations are running and still not finished.

To clarify, I am not using BehaviorSpace,  I am using pynetlogo interface to run Netlogo from my python code. I use ipyparallel to run 1000'000 Netlogo simulations in parallel. 
I am running my program on our high-performance computing cluster on about 100 nodes, 2G each, so there is no memory limit there. 

Here are the list of what I have done so far:

1. in pynetlogo I set gui=False which does jpype.java.lang.System.setProperty('org.nlogo.preferHeadless', 'true')
is it same as what you recommended "-Dorg.nlogo.noGenerator=true"
2. I pass these arguments while calling Netlogo
jvmargs=['-Xms16M', '-Xmx512M', '-XX:-UseCompressedClassPointers']
3. I kill each netlogo instance after it is finished
netlogo.kill_workspace()

Thanks for your help and suggestions.

**Comment by NedaMarvasti** [comment]
I am closing this issue, because the problem is solved. Thanks for your help.

**Comment by LaCuneta** [comment]
Thank you for the extra information!  It's very good to have if we get similar reports in the future.

> 1. in pynetlogo I set gui=False which does jpype.java.lang.System.setProperty('org.nlogo.preferHeadless', 'true')
>    is it same as what you recommended "-Dorg.nlogo.noGenerator=true"

These properties would be different, but it sounds like not using the compressed class pointers and killing off the workspaces after use was enough to get things working for you.

**Comment by SethTisue** [comment]
> I kill each netlogo instance after it is finished
netlogo.kill_workspace()

I would expect this to be the key change.
