### ISSUE TITLE
readme.md gives no advice about where to look in case of problems

### ISSUE THREAD

**Issue by mars0i** [NetLogo/NetLogo#1805]
I installed NetLogo 6.1.1 on MacOS Catalina 10.15.2 and it wouldn't run.  After a lot of experimentation, searching on the MacOS error I got, installing 6 .1.0 (same problem), looking at the release notes page, and checking all of most recent issues in github, I found this page https://github.com/NetLogo/NetLogo/wiki/Known-Issues by doing a web search for "netlogo catalina".   The 'xattr' solution there solved the problem--great! 

I just want to suggest that there better pointers for help in the readme, which says, for Mac, only "Double click on the NetLogo icon in the NetLogo folder."   I don't think every startup or installation issue has to be listed in the readme, but a pointer to good places to look for solutions that have already been established would be helpful.

Thanks!

**Comment by SethTisue** [comment]
(the readme in question being https://github.com/NetLogo/NetLogo/blob/hexy/dist/readme.md , not the repo readme on GitHub)

**Comment by mars0i** [comment]
Yes.  I should have thought to clarify that.

**Comment by LaCuneta** [comment]
Thank you for reporting your trouble in finding the workaround, we appreciate it.  This issue was supposed to be corrected previously, so if you wouldn't mind checking on a couple more things for me, it'd be very helpful.

Can you check that **Allow apps downloaded from:** is set to **App Store and identified developers** in the macOS [Security and Privacy settings General tab](https://support.apple.com/en-us/HT202491) for me?  If it is set to only allow **App Store** apps, that's likely the problem, and I've updated our docs to be clearer about that.

If it *is* set to allow from identified developers and still didn't work, can you run the below commands for me in a terminal window?  You may need to tweak the paths to be appropriate for your system, and/or [re-download the 6.1.1 disk image](http://ccl.northwestern.edu/netlogo/6.1.1/) if you deleted it already.

```
spctl -a -vv /Applications/NetLogo\ 6.1.1/NetLogo\ 6.1.1.app
spctl -a -t open --context context:primary-signature -v ~/Downloads/NetLogo-6.1.1.dmg
```

And thanks again!

**Comment by mars0i** [comment]
Thanks @LaCuneta.  

I checked, and I did have "App Store and identified developers" selected previously.

Next I moved the 6.1.1 folder to the trash, re-downloaded and installed, then verified that the problem recurs.  Then I did the following, and the commands you suggested didn't seem to have any effect.  I was able to run NetLogo successfully again after executing the `xattr` line.
```
~$ spctl -a -vv /Applications/NetLogo\ 6.1.1/NetLogo\ 6.1.1.app
/Applications/NetLogo 6.1.1/NetLogo 6.1.1.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: Northwestern University (E74ZKF37E6)
~$ spctl -a -t open --context context:primary-signature -v ~/Downloads/NetLogo-6.1.1.dmg
/Users/marshall/Downloads/NetLogo-6.1.1.dmg: accepted
source=Notarized Developer ID
~$ open /Applications/NetLogo\ 6.1.1/NetLogo\ 6.1.1.app
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/NetLogo 6.1.1/NetLogo 6.1.1.app.
~$ sudo xattr -dr com.apple.quarantine /Applications/NetLogo\ 6.1.1/NetLogo\ 6.1.1.app
Password:
~$ open /Applications/NetLogo\ 6.1.1/NetLogo\ 6.1.1.app
~$ ls -l ~/Downloads/
total 426048
-rw-r--r--@ 1 marshall  staff  215398464 Jan  4 11:59 NetLogo-6.1.1.dmg
~$
```
(I don't think it matters, but after reinstalling and before executing the `spctl` lines, I had moved the new dmg file to the trash after copying the NetLogo folder to /Applications, but then I restored the dmg file to ~/Downloads when I realized that it needed to be there for these comments.)

(fwiw this is a fairly new machine.  I think it came with MacOS 10.14, but I immediately installed 10.15.1, and then got to 10.15.2 with another update install, iirc.  I've had some funny things happen in the past with machines that are old and have a lot of odd configuration things left over from the past.)

**Comment by beaugunderson** [comment]
just hit this as well on 10.15.4 with a new download of 6.1.1; this fixed my issue:

```
sudo xattr -dr com.apple.quarantine /Applications/NetLogo\ 6.1.1/NetLogo\ 6.1.1.app
```
