### ISSUE TITLE
Moving a Turtle Multiple Times

### ISSUE THREAD

**Issue by jessicagn** [NetLogo/NetLogo#1816]
Hi, I've been working on programming a slightly complicated model in NetLogo and there's one part that I'm struggling to determine how to write. I have two types of breeds for turtles in my model, we'll call them breed 1 and breed 2. For every time step, breed 1 moves once, while breed 2 should move four times. The part I'm struggling to implement is that breed 2 should move once, four times. In other words. A random turtle is chosen, then moved. For each time step breed 1 will only be chosen once, but breed 2 should be chosen four times. Any ideas of how to implement this would be awesome!

**Comment by brandesNW** [comment]
Hi Jessica,
I think  n-of<https://ccl.northwestern.edu/netlogo/docs/dictionary.html#n-of> will do what you want.
Just be sure you have at least  4 turtles of breed 2 .

Simple example:

breed [ breed1s breed1 ]
breed [ breed2s breed2 ]

to setup
  clear-all
  create-breed1s 10 [ set color blue set heading random 360 ]
  create-breed2s 10 [ set color red set heading random 360 ]
  reset-ticks
end

to go
  tick
  ask one-of breed1s [ move ]
   ask n-of 4 breed2s [ move ]
end

to move
  rt (random-float 60) - 30
  fd 1
end

Aaron

**Comment by jessicagn** [comment]
Hi Aaron, Thank you for your input! The problem with that is that I want the turtles to be selected randomly, and if I understand it correctly, wouldn't that have breed 1 move, then breed 2 move?

**Comment by brandesNW** [comment]
Hi Jessica,
In the following the primitive turtle-set<https://ccl.northwestern.edu/netlogo/docs/dictionary.html#turtle-set> is used to put all the turtles in one set.  n-of 5 then randomizes the order


to go
  ask  n-of 5 (turtle-set one-of breed1s n-of 4 breed2s) [ move ]
  tick
end

If for some reason you want to see that the turtles are moving in a random order you can make them into a list, and use foreach<https://ccl.northwestern.edu/netlogo/docs/dictionary.html#foreach> to iterate over them.
This code is a bit more “advanced” because it makes use of an anonymous procedure<https://ccl.northwestern.edu/netlogo/docs/dictionary.html#arrow>.

to go
  let turtle-list (list n-of 5 (turtle-set one-of breed1s n-of 4 breed2s))
  foreach turtle-list [
    x -> ask x [ ; x is the turtle
      move
    ]
  ]
  tick
end

Aaron

**Comment by brandesNW** [comment]
Hi Jessica,
Since you had a request for help, and not a bug (issue) to report, I am closin

**Comment by brandesNW** [comment]
Hi Jessica,
Since you had a request for help, and not a bug (issue) to report, I am closing this as an issue. If you have more questions in the future I encourage you to  make use of our main online user community list  [NetLogo Users Group](https://groups.google.com/d/forum/netlogo-users). There you can discuss thoughts and questions about NetLogo with other users via email or the web. Follow the above link to browse the group, or follow  [this link](https://groups.google.com/d/forum/netlogo-users) to join.
- Aaron
