### ISSUE TITLE
how can I use is-<breed>?

### ISSUE THREAD

**Issue by jinjin9527** [NetLogo/NetLogo#1852]
When I use it, "Nothing named IS-\<BREED\> has been defined."
What I tried is is-\<light\>?, is-\<lights\>?, is-\<breed\>?, is-\<breeds\>
And my code is

let blocked-patch next-blocked-patch  ;blocked-patch may be lights or cars 
let yellow-light-blocked? is-\<light\>? with [ color = yellow ] blocked-patch  ;I want to know wether or not blocked by yellow light.'

**Comment by brandesNW** [comment]
Thanks for contacting us about your problem.  
I will briefly explain why it is not a NetLogo bug, and then offer some programming ideas.

The error message appears because no breed has been defined.
If a breed were defined in the code with the statement
`breed [lights light]`

Then the correct syntax for the command you are looking for would be `is-light?`
The angle brackets in `is-<breed>? `mean that the letters <breed> should be replaced by the actual name for a single member of the breed. 

Programming help:
Breeds are turtles that belong to a group. Commands can be addressed to turtles of a breed.
If you want to learn about using breeds, here are some resources:
[NetLogo Programming Manual - breeds](https://ccl.northwestern.edu/netlogo/docs/programming.html#breeds)
[NetLogo Dictionary - breed](http://ccl.northwestern.edu/netlogo/docs/dict/breed.html)

You got an error message because you did not define any breeds.

A quick way to open an example of using breeds from the NetLogo Model Library is to type “___Breed” in the command center. Type only the characters in the quotes. It begins with three underscores.

If you create breeds for cars and lights, you can test if a car is on the same patch as other cars or lights using
`cars-here` or `patches-here`

[Documentation for turtles-here](https://ccl.northwestern.edu/netlogo/docs/dictionary.html#turtles-here)

If you create a procedure called move for cars, you can get them all to move using the command
ask cars [ move ]

The NetLogo model in the attached zipped file gives a simple example of a car that stops at yellow lights and not green lights.
[light-breed.nlogo.zip](https://github.com/NetLogo/NetLogo/files/5007476/light-breed.nlogo.zip)

If you have more questions in the future I encourage you to make use of our main online user community list  
[NetLogo Users Group](https://groups.google.com/d/forum/netlogo-users). 
There you can discuss thoughts and questions about NetLogo with other users via email or the web. Follow the above link to browse the group.

Have Fun!

**Comment by jinjin9527** [comment]
Thank you for answering and simple code!
[is-light] worked!
