### ISSUE TITLE
Can not move inspection monitor to second of dual screens

### ISSUE THREAD

**Issue by dougedmunds** [NetLogo/NetLogo#1859]
Win10 home
NL 6.1.1
Dual display system (dual monitor system, display 1, display 2)

Situation1: NetLogo opened in Display 1.   Monitors open in Display 1
BUG:  I cannot move inspection monitors opened in display 1 to display 2.

Situation2: NetLogo opened in Display 2.  Monitors open in Display 2
BUG:  I can move inspection monitors from display 2 to display 1, but cannot move them back to display 2.

In both cases, if a Monitor is in Display 1, it will not move into Display2 

![dual_screen00](https://user-images.githubusercontent.com/616048/93814231-18d8fb80-fc09-11ea-99f9-f37307907f7f.png)
![dual_screen01](https://user-images.githubusercontent.com/616048/93814252-20000980-fc09-11ea-86bd-f6ddf9cf59ee.png)
![dual_screen02](https://user-images.githubusercontent.com/616048/93814270-29897180-fc09-11ea-810c-e11ad9a387db.png)
![dual_screen03](https://user-images.githubusercontent.com/616048/93814301-30b07f80-fc09-11ea-8936-970efa045c30.png)

**Comment by brandesNW** [comment]
I have observed the same behavior on a Mac.

**Comment by brandesNW** [comment]
Hi Doug,
I’m sorry you have encountered this problem. I have verified that it also happens in MacOs.
The problem seems to be specific to the inspectors and does not occur with Color Swatches, The Turtle Shapes Editor, the extra NetLogo3D window and other.
We will keep you informed of any progress we make with this issue.
Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling
