### ISSUE TITLE
MacOS Big Sur

### ISSUE THREAD

**Issue by Jotapafc** [NetLogo/NetLogo#1884]
Hey there!

I couldn't install the NetLogo 3D 6.0.2 on my Mac which is running with MacOS Big Sur Version 11.1. Could you please advise?

**Comment by LaCuneta** [comment]
Hey @Jotapafc, thanks for your interest in NetLogo.  You can try the workaround from [this comment](https://github.com/NetLogo/NetLogo/issues/1302#issuecomment-281407451), just use the path to NetLogo 3D 6.0.2 instead of the one there for NetLogo 6.0.  If that doesn't work, I'd recommend trying to [download and use NetLogo 3D 6.2.0](http://ccl.northwestern.edu/netlogo/download.shtml), which was recently released and has better support for macOS Big Sur's Gatekeeper's notarization process.

**Comment by brandesNW** [comment]
Hi,
Thanks for contacting us, and sorry you have encountered a problem.

I would advise installing our newly released version NetLogo 6.2.0, unless you have a very strong reason for using a previous version.

For a typical installation you should find the executable “NetLogo 3D 6.2.0.app” file in the “Applications/NetLogo 3D 6.2.0” folder which also contains the “NetLogo 6.2.0.app”
Double clicking on the “NetLogo 3D 6.2.0.app” file should open it.

Please let us know if you have any further questions.
Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling

**Comment by Jotapafc** [comment]
Many thanks! I'll try this new version.
