### ISSUE TITLE
Migrate binary artifacts off of bintray to a new home

### ISSUE THREAD

**Issue by romainreuillon** [NetLogo/NetLogo#1915]
Dear Devs,

it seems that the jar of NetLogo is no more available on bintray:
https://dl.bintray.com/netlogo/NetLogo-JVM/org/nlogo/netlogo/6.2.0/

I think bintray has retired. 

Would it be possible to make this jar accessible on another repository?

Best regards,
Romain

**Comment by LaCuneta** [comment]
Hey Romain, thank you for opening the issue.  We are aware of bintray's coming demise and are working on migrating to another host.  We'll update here and close this once that's complete, hopefully pretty soon.

**Comment by romainreuillon** [comment]
Actually for the time being, it seem that it might be just a maintenance of bintray. I may have overreacted :)

https://status.bintray.com/

**Comment by LaCuneta** [comment]
No worries at all, it is still good to have an issue open to track the migration before the final drop-dead date of May 1st.

**Comment by LaCuneta** [comment]
With [this commit](https://github.com/NetLogo/NetLogo/commit/d27b502196ff975bab2c5690c09a9f41a9ea09e5) and some related work in other repositories, our current binary artifacts are now available [on Cloudsmith](https://cloudsmith.io/orgs/netlogo/), including NetLogo jars from the official release versions back to 5.3.1.  If anyone stumbles on this and notices something we missed or has a need for us to publish an old, non-release jar, just leave a comment here or post in the NetLogo devel Google Group.

You can reference NetLogo in sbt projects like so (in a typical `build.sbt` file):

```scala
resolvers += "netlogo" at "https://dl.cloudsmith.io/public/netlogo/netlogo/maven/"
libraryDependencies += "org.nlogo" % "netlogo" % "6.2.0"
```

**Comment by lucoxlee** [comment]
![image](https://user-images.githubusercontent.com/16668518/134465527-227ef814-a8ab-4e73-b1d3-36dfbd06fd15.png)
```
https://repo1.maven.org/maven2/org/nlogo/netlogo-extension-documentation_2.12_1.0/0.8.0/netlogo-extension-documentation-0.8.0.pom
```
i need to  bulid tag 6.2.0,
when i run ```./sbt all```,
got dependencies 404.
![image](https://user-images.githubusercontent.com/16668518/134465802-50ca08a4-14bf-4c8c-a812-2fae44924f98.png)
where should i add
```
resolvers += "netlogo" at "https://dl.cloudsmith.io/public/netlogo/netlogo/maven/"
libraryDependencies += "org.nlogo" % "netlogo" % "6.2.0"
```
in build.sbt

**Comment by LaCuneta** [comment]
@lucoxlee 

**If you can explain more about why you need to build NetLogo from the `6.2.0` tag, I might be able to provide more helpful information**.

> where should i add `...` in build.sbt

If you just need a copy of `netlogo-6.2.0.jar` to use in a project, we already have one hosted on Cloudsmith.  You can add a dependency as normal to your project's `build.sbt` file.  If your `build.sbt` only defines a single project (as most do) you can add those lines anywhere.  You do not need to build or package NetLogo directly to do this.  If your project is not Maven/sbt-based and you just need the jar file, you [can download it directly from Cloudsmith](https://cloudsmith.io/~netlogo/repos/netlogo/packages/detail/maven/netlogo/6.2.0/a=noarch;xg=org.nlogo/#files) and use it that way.

You can see an example of this in [Behaviorsearch's `build.sbt` file](https://github.com/NetLogo/behaviorsearch/blob/master/build.sbt#L9-L32).  Behaviorsearch does a little extra work for the `libraryDependencies ++=` part that you can ignore (it does that as it's bundled with NetLogo, too).

> i need to bulid tag 6.2.0,

Pulling the latest `hexy` would be much easier to build than `6.2.0` as all updates for Cloudsmith will be done in NetLogo and its bundled extensions and apps.  The latest `hexy` does not have a lot of changes since `6.2.0`, it's pretty similar.  If you need an "official" release tag to build, you could use `6.2.1-beta1` which is out now.

> when i run ./sbt all, got dependencies 404.

If you're just building NetLogo `6.2.0` tag to get a `netlogo-6.2.0.jar` file, you don't need to run `./sbt all` (which builds all extensions and a few other things), you should be able to do a `./sbt netlogo/package` and you'll find the jar in `netlogo-gui/target/`.

Running `./sbt all` will build NetLogo and all extensions, and the extensions are the ones that use the `netlogo-extension-documentation` and `netlogo-extension` sbt plugins that will be missing on bintray.  If you really need to do this, then you will need to update each bundled extension to point to the new Cloudsmith location, [like this](https://github.com/NetLogo/CSV-Extension/commit/49a5163bc8b831051d5c01c13c54c0c84e1f90d0).  Or you can update each extension submodule to their latest commit, which will include those changes already.  Using `hexy` latest will also get these updated extensions.
