### ISSUE TITLE
NetLogo work on the Macbook Air/Pro with M1 chip?

### ISSUE THREAD

**Issue by nwijermans** [NetLogo/NetLogo#1951]
I am in the process of buying a new computer and checking whether this would work.
Any idea whether this is handled by Rosetta? 

Thanks!

Best wishes, Nanda

**Comment by LaCuneta** [comment]
Hi Nanda, thanks for your interest in NetLogo.  I would expect Apple to work hard to get Java apps running correctly, as there are a lot of them out there besides NetLogo.  But our development team doesn't have one, so we don't have "official" confirmation.

We have had a couple user reports of success running on an M1.  The [NetLogo users group](https://groups.google.com/g/netlogo-users) might be a good place to confirm.

If anyone else sees this and can add more info, that would be appreciated.

**Comment by CIVITAS-John** [comment]
I can confirm that NetLogo works on my M1 Pro machine. I don't know if all extensions work though.

Since we bundle Java into our release, it seems reasonable to upgrade it to something that natively supports ARM to get the best performance out. But maybe we have already done that by upgrading Java 15.

**Comment by LaCuneta** [comment]
Thanks @CIVITAS-John!  We've got issue #2016 to track bundling an M1/M2-native JVM with NetLogo, too.
