### ISSUE TITLE
First turtle created after start may draw incorrectly

### ISSUE THREAD

**Issue by darian23** [NetLogo/NetLogo#1978]
### Test Procedure:

Run the following command in a newly opened instance of NetLogo from a button control or the startup procedure.

`crt 2 [ pd jump 2 ]`

### Result:

Two turtles appear in the drawing area each displaced from the origin by 2 units.  One turtle has drawn a line to its position from the origin but the other has not.

### Expected Result:

Both turtles should draw a line segment of length 2 from the origin to their positions.

### Notes:

- EDIT:  The unexpected behavior also occurs if the command is entered in the command center as the first action upon starting NetLogo.
- The unexpected behavior only occurs with the first turtle used to draw after NetLogo starts.  
- If the first turtle to be created is destroyed without having moved with its pen down, then the unexpected behavior occurs in the second turtle. 
- If `forward` is used instead of `jump` in the turtle commands then the first unit of the first turtle's drawing is missing but the second unit is drawn correctly.  
- It does not seem to matter if `clear-all` is called first, nor if any other turtle commands such as `setxy`
 which do not draw are called first.
- The unexpected behavior occurs with both continuous updates and updates on ticks.
- Using 64-bit Windows 10, this works as expected in NetLogo 6.0 and 6.0.4, but the unexpected behavior is confirmed to occur in 6.1.0, 6.2.0 and 6.2.1.
- The unexpected behavior is also confirmed to occur in 6.2.1 under 64-bit Linux, and under 64-bit Windows 10 using the 32-bit built of NetLogo.

This zipped .nlogo file has a `startup` procedure which demonstrates the unexpected behavior: [first_turtle_draw_bug.zip](https://github.com/NetLogo/NetLogo/files/7477990/first_turtle_draw_bug.zip)

**Comment by LaCuneta** [comment]
Thank you for the detailed error report.  You are correct about the regression being in NetLogo 6.1.0 (and later).  I just fixed a related bug with `import-drawing`, and confirmed this is an issue as well.  

The quick workaround is just to use any command that would draw anything once, and then drawing should work normally for the rest of the time the model is open.   `create-turtles 1 [ pd fd 1 ] clear-all` in `startup` or the first line of a `setup` procedure would do the trick. 

This issue is with [this statement in the `TrailDrawer.scala`](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/src/main/render/TrailDrawer.scala#L178-L180).  It should not have an `else`, it should just run the drawing code after setting up the image when its null.

**Comment by SethTisue** [comment]
nice catch and thorough bug report!

**Comment by LaCuneta** [comment]
The fix is [on a branch](https://github.com/NetLogo/NetLogo/tree/first-draw-fix) but we're in code freeze for a release so it'll get merged after that goes live.

**Comment by EwoutH** [comment]
> The fix is [on a branch](https://github.com/NetLogo/NetLogo/tree/first-draw-fix) but we're in code freeze for a release so it'll get merged after that goes live.

Could you explain a bit more about how this process works? Shouldn't such a bug fix be in the 6.2.2 release?

Also, would a maintenance branch for 6.2.x be useful? Then regular development (towards 6.3 or 7.0 I assume) can continue, while essential bugs could get backported to 6.2.x.
