### ISSUE TITLE
Non-Integer patch-size leads to import-pcolors-rgb not filling the complete view 

### ISSUE THREAD

**Issue by gabriel-wurzer** [NetLogo/NetLogo#2028]
Given: ![some png image](https://user-images.githubusercontent.com/35217861/165350790-ea589e47-e7f1-47d5-8b63-0c933eb183eb.png) with dimensions 145x113 pixels, a view that is exactly the same size [origin in left-lower corner, min-pxcor=0, min-pycor=0, max-pxcor=144, max-pycor=112].

Expectation: `import-pcolors-rgb` covers all patches.

What actually happens:

- if patch-size is set to a non-integer (e.g. 2.7586206896551726), the last column is not being set. can be tested with `ask patches with [not is-list? pcolor][set pcolor red]`.
- for patch-size being an integer (e.g. 2), the result is just what I expect.

Solution / suggestion
- I know this is due to rounding issues, but can this somehow be overcome with rounding?

Note: 
this behavior might apply to import-pcolors as well.

**Comment by gabriel-wurzer** [comment]
P.S. as a quick and dirty solution (which satisfies expectations), might also check if img.xsize = world-width && img.ysize == world-height and then copy each pixel to its cell; but maybe there's a more elegant way to do that ...

**Comment by brandesNW** [comment]
Hi,
One thought is to import the file with integer size patches and then resize the patches. This gave me a reasonable result when the image was a close but not exact fit to the view.

extensions[bitmap]

to setup
  ca
  let orig-patch-size patch-size
  let image-file user-file
  let image bitmap:import image-file
  let height bitmap:height image
  let width bitmap:width image
  resize-world 0 width - 1 0 height - 1
  set-patch-size 1
  import-pcolors-rgb image-file
  set-patch-size orig-patch-size
end

Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: gabriel-wurzer ***@***.***>
Reply-To: NetLogo/NetLogo ***@***.***>
Date: Tuesday, April 26, 2022 at 12:52 PM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NetLogo/NetLogo] Non-Integer patch-size leads to import-pcolors-rgb not filling the complete view (Issue #2028)


Given: [some png image] <https://urldefense.com/v3/__https:/user-images.githubusercontent.com/35217861/165350790-ea589e47-e7f1-47d5-8b63-0c933eb183eb.png__;!!Dq0X2DkFhyF93HkjWTBQKhk!DmnHpR1AwIMqOfbXYjhjzm6M_PB2vOF0jer-o0qRwnxpyRnIP83NjzI54GgJkwnc8j9bnevfhg$> with dimensions 145x113 pixels, a view that is exactly the same size [origin in left-lower corner, min-pxcor=0, min-pycor=0, max-pxcor=144, max-pycor=112].

Expectation: import-pcolors-rgb covers all patches.

What actually happens:

  *   if patch-size is set to a non-integer (e.g. 2.7586206896551726), the last column is not being set. can be tested with ask patches with [not is-list? pcolor][set pcolor red].
  *   for patch-size being an integer (e.g. 2), the result is just what I expect.

Solution / suggestion

  *   I know this is due to rounding issues, but can this somehow be overcome with rounding?

Note:
this behavior might apply to import-pcolors as well.

**Comment by gabriel-wurzer** [comment]
...hadn't thought about that one - great! This fixes my problem!

**Comment by brandesNW** [comment]
I plan to reclose the issue, since it was resolved to the user's satisfaction, and the behavior does not seem fully specified by the NetLogo [definition of import-pcolors-rgb](https://ccl.northwestern.edu/netlogo/docs/dictionary.html#import-pcolors-rgb).
However, I am actually unable to reproduce the error, and am curious about the user's system specifications. They are available under the `About NetLogo` menu item which is under the `NetLogo` menu item on MacOS, and under the Help menu item on other OSs. Clicking on the `System` tab will show the info which can be copied and pasted.
After unzipping the attachment, either of the models can be used to test whether the import works as described in the reported issue. The initial condition (automatic with the startup version, require pressing the setup version) used the values and image file specified in the bug report. Pressing go allows the user to vary the patch value. I did not get any red non-rgb patches under any condition I tested
[import pcolors patchsize.zip](https://github.com/NetLogo/NetLogo/files/8604257/import.pcolors.patchsize.zip)
.

**Comment by gabriel-wurzer** [comment]
Thank you for testing this, 
seems the culprit was not `import-pcolors` but `import-a:pcolors` in the import-a extension. I have produced a minimal working example (based on your code) which shows  `import-pcolors` vs. `import-a:pcolors`  --> [import-a pcolors patchsize.zip](https://github.com/NetLogo/NetLogo/files/8609003/import-a.pcolors.patchsize.zip). 

After unzipping, press `setup-import-pcolors` and see that all is fine, then press `setup-import-a-pcolors` and choose 145x113pixels.png. You will see the following image:

![import-a-pcolors](https://user-images.githubusercontent.com/35217861/166420814-0f214f18-eddf-4324-aef8-c003283f5375.png)

System Info:

NetLogo 6.2.0 (December 22, 2020)
Extension API version: 6.1
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.12
Java heap: used = 37 MB, free = 407 MB, max = 910 MB

JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)

Extensions:
Import-A Extension 1.0.6 (=latest version)
Fetch Extension 1.0.4 (=latest version)

**Comment by gabriel-wurzer** [comment]
Dear Aaron,
You're absolutely right - here is the correct zip: [import-a pcolors patchsize.zip](https://github.com/NetLogo/NetLogo/files/8612741/import-a.pcolors.patchsize.zip) is the correct file (corrected also in the previous comment!)
Gabriel

**Comment by brandesNW** [comment]
This is an extension import-a issue
