### ISSUE TITLE
Arrow (`->`) is listed in the "Built-In Variables" section of dictionnary

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#2118]
The [dictionary](https://ccl.northwestern.edu/netlogo/docs/dictionary.html) lists [->](https://ccl.northwestern.edu/netlogo/docs/dictionary.html#arrow) within its own "Other" category under the "Built-In Variables" section of dictionary.

It seems to be on purpose given that someone went through the trouble of creating a whole category for it. Maybe I'm missing something, but I fail to see how the arrow is a variable. Should it be removed from that section?

(Note that `->` is also listed under the "Anonymous Procedures" category, so there is a link to it in a sensible place already.)

**Comment by LaCuneta** [comment]
Thanks for pointing this out!  This is fixed [here](https://github.com/NetLogo/NetLogo/commit/ab08262def527136060951f9ec8b72605b316ad9) and I'll merge it once tests pass.  I really wanted to know how this would happen, as it is very intentional looking.  The answer is [a conversion of the old `?` placeholder to the arrow](https://github.com/NetLogo/NetLogo/pull/1280/commits/a2590e46074bfaada437499e2a8bad2e199ddf8b).  Mystery solved!

**Comment by nicolaspayette** [comment]
> The answer is [a conversion of the old ? placeholder to the arrow](https://github.com/NetLogo/NetLogo/pull/1280/commits/a2590e46074bfaada437499e2a8bad2e199ddf8b). Mystery solved!

Oh! Makes sense. Thanks for doing the archeology. It would have nagged at me for a while otherwise. :-)
