### ISSUE TITLE
BehaviorSpace updates plots when running headlessly

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/NetLogo#2120]
A user was having trouble hitting memory limits running a very large model for a very large number of ticks.  When they'd get the out of memory exception, they noticed that it was usually in some code to update the plots.  They reached out to confirm that plots are updating during headless BehaviorSpace runs, and I confirmed that they are.  I advised them of a workaround to avoid running the plots, splitting out `tick` into `tick-advance` and adding a check of `behaviorspace-experiment-name` to `update-plots`:

```netlogo
to go
  ; ... model code ...
  tick-advance 1
  if behaviorspace-experiment-name = "" [ update-plots ]
end
```

The user was surprised and the behavior does seem odd.  I could see a situation where a user wanted to export plot data for use at the end of a run, but that seems like a rare situation.  I think most users running headlessly wouldn't expect the plots to run.

To confirm it was an issue, I ran the Red Queen Beta2 experiment at 1 repetition for 500,000 ticks.  I monitored memory usage using VisualVM.  Max heap usage by the end was over 1.8gb and min was creeping up linearly up to 750mb.  I then added the workaround and re-ran the same experiment.  Max never got above 300mb and was about 130mb by the end with no linear increase.  I didn't measure runtimes but I suspect disabling the plots would only help there, too.  This is a crude measurement, but the effects are pretty dramatic with only 2 plots with 2 pens each.   

My feeling is that plots should be disabled by default when running headlessly, and we should provide a switch (both command line and GUI) to enable them if their output is needed.  We could even add an explanatory warning if any of the `export-world`, `export-plot`, or `export-all-plots` prims are used to try to avoid any confusion as to why they are empty.

Relatedly, I checked and confirmed that monitors do not update when running headlessly, just as something else that could slow down a headless run without a benefit.

**Comment by umit1010** [comment]
I agree that the plot updates should be disabled by default in BehaviorSpace. 

It would be great to have plots turned off by default in BehaviorSpace but provide users an interface element (eg, checkbox) to enable plotting, an equivalent NetLogo_Console parameter for running experiments via the terminal. 

I am assuming many people are churning away many hours of time without realizing their experiments could run more efficiently. 

However, there's something more
important than memory efficiency in this case: _losing time_. 

A higher memory requirement means either significantly slower execution or using fewer CPU cores than available because they cannot allocate enough memory to each thread. For example, if one has a system with a 10 core CPU and 16 GB of ram, and their model is using max memory of 2gb per thread when plots are updating in headless mode, they'd need 20gb+ available memory to be able to use all 10 cores efficiently. So, if they are running the experiment on an OS with swapping, they'd experience slower execution; otherwise their experiment would simply fail and they'd find themselves repeating the experiment with 6-8 cores instead of using all 10 cores available for them. In either case, the loss of time is much more painful than the loss of efficiency (or the higher electricity bill).

**Comment by brandesNW** [comment]
The warning messages are now only issued once.
It seems that the warning message only appears once the first run is complete. This could take a long time for some experiments. Is there a way to avoid this?
It also seems that the step numbers, but not the run numbers don't update until the warning dialog is dismissed.

**Comment by brandesNW** [comment]
fix was merged
