### ISSUE TITLE
add `switch` or `case` statement, and/or `cond`, to language

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#344]
Uri writes:

> in the past weeks, several colleagues hve complained to me about
> netlogo not having a case or switch. I agree that nested if-elses
> are a drag.  I know we've had this on our list for years.  How
> hard would it be to do?

We had a devel meeting about this circa 2005 and nobody liked any of the syntaxes that were proposed.  They all involved an awful lot of square brackets that nobody could see how to get rid of.

We could do it again and then just bite the bullet and pick the least bad syntax we can think of. The actual coding on this would not be a huge project, just a medium sized one (for someone who knows the compiler and engine).

Berkeley Logo has both `case` and `cond`.  (We might decide that if we support `cond`, we don't need `case`.)

`case` example from Berkeley Logo manual:

```
to vowelp :letter
output case :letter [ [[a e i o u] "true] [else "false] ]
end
```

`cond` example from Berkeley Logo manual:

```
to evens :numbers   ; select even numbers from a list
op cond [ [[emptyp :numbers] []]
          [[evenp first :numbers]  ; assuming EVENP is defined
           fput first :numbers evens butfirst :numbers]
          [else evens butfirst :numbers] ]
end
```

Lots of brackets, very Lisp-y.

An example of when you want `cond`, from @reuven's Autumn model:

```
to set-shape-for-value [value]
  ifelse value > 75 [ set shape "default" ]
  [ ifelse value <= 25 [ set shape "default one-quarter" ]
    [ ifelse value <= 50 [ set shape "default half" ]
                         [ set shape "default three-quarter" ]]]
end
```

If we adopted the Berkeley `cond` syntax this would be:

``` text
to set-shape-for-value [value]
  cond [ [[value >  75] set shape "default" ]
         [[value <= 25] set shape "default one-quarter" ]
         [[value <= 50] set shape "default half" ]
         [else          set shape "default three-quarter" ] ]
end
```

This reads OK, but is hard to remember exactly how to write.

An example of when you want `case`, from Heat Diffusion:

``` text
to update-alpha
  ifelse (material-type = "wood") ;; wood
  [ set alpha 0.00128 ]
  [ ifelse (material-type = "stone") ;; stone
    [ set alpha 0.012 ]
    [ ifelse (material-type = "iron")  ;; iron
      [ set alpha 0.2034 ]
      [ ifelse (material-type = "aluminum") ;; aluminum
        [ set alpha 0.8418 ]
        [ ifelse (material-type = "silver")  ;; silver
          [ set alpha 1.7004 ]
          [ user-message "Choose your own value for alpha!" ] ] ] ] ]
end
```

If we adopted the Berkeley `case` syntax this would become:

``` text
to update-alpha
  case material-type
   [ [ ["wood"]     set alpha 0.00128 ]
     [ ["stone"]    set alpha 0.012   ]
     [ ["iron"]     set alpha 0.2034  ]
     [ ["aluminum"] set alpha 0.8418  ]
     [ ["silver"]   set alpha 1.7004  ]
     [ else user-message "Choose your own value for alpha!" ] ]
end
```

Again, this reads OK, but is hard to remember exactly how to write.

**Comment by mars0i** [comment]
A variant on qiemem's proposal, but with conditions in reporter blocks:

````netlogo
(cond [value > 75]  [ set shape "default" ]
      [value <= 25] [ set shape "default one-quarter" ]
      [value <= 50] [ set shape "default half" ]
      true          [ set shape "default three-quarter" ])
````
Is the only thing holding back implementation of `cond` or `case` disagreement about syntax? I understand that syntax has to be thought through, since it has long-term impacts.  Still, anyone who's done more than trivial NetLogo programming has wanted a `case` or `cond` at some point.  I think we'd all like to have something that allows avoiding embedded `if-else`s.  I would think `cond` or `case` would be easy to implement.  I agree that since `cond` is more general, that would be the first that should be implemented, even though it's less common outside of the Lisp-ey world.  (If the only *easy* way to add `cond` involves lots of brackets, why not offer a many-bracket version at first, with the option of adding a cleaner syntactically sugared version later?)

As for `cond-value`, that will be used less often than a procedural `cond`, I suspect, so if it's extra trouble to implement `cond-value`, that could wait.

My 2c.  Thanks!

**Comment by qiemem** [comment]
I've created an extension that experiments with a possible syntax: https://github.com/qiemem/ControlFlowExtension

**Comment by SethTisue** [comment]
awesome

**Comment by qiemem** [comment]
The `cf` extension has been out for a while now, and we've learned some lessons from it. Namely:

- The verbosity of its syntax is a pain
- The performance impact of the way it constructed lists of condition/consequent pairs is unacceptable

The new proposal is to accomplish this by simply making `ifelse` and `ifelse-value` variadic:

```
(ifelse
  value > 75  [ set shape "default" ]
  value <= 25 [ set shape "default one-quarter" ]
  value <= 50 [ set shape "default half" ]
              [ set shape "default three-quarter" ])
```

The default number of arguments would be 3, so current `ifelse` would continue to work. We had been discussing add a new primitive with that syntax, but the fact that the syntax is just a generalization of `ifelse` pushed us towards generalizing `ifelse`.

In addition to generalizing `ifelse` and `ifelse-value`, we would change the associativity of `ifelse-value` in accordance with #588.

That said, this is a substantial change to `ifelse` with a very hard break in forwards compatibility (new models wouldn't work in old version of NetLogo).

The change to `ifelse-value` does break backwards compatibility, but affects a very limited number of models (1 in the models library and 3 on the modeling commons) and should be auto-convertible.

The current plan is to:

- Replace the current primitives in `cf` with the generalized `ifelse` and `ifelse-value`  to test the syntaxes and let people start using them as soon as possible.
- Assuming there are no problems that arise, move the change into the core language at a significant version change (major or minor, not point).

Note that the above variadicity is accomplished by having them take anonymous procedures instead of  blocks. Benchmarking has shown no performance impact, both on micro benchmarks as well as real models. That said, there could be unintended consequences, so further testing and benchmarking are needed.

**Comment by SethTisue** [comment]
I like it

**Comment by jbadham** [comment]
The NetLogo dictionary example for multiple choice ifelse does not work 'out of the box'. It uses the cf implicitly, but v6.0.4 requires an explicit extension statement and call to cf. See https://stackoverflow.com/questions/56535452/assigning-patch-values-from-raster-data-in-netlogo/56538303#56538303

**Comment by LaCuneta** [comment]
@jbadham Good point, I'll update the docs to note that the variadic behavior was new as of 6.1.

Side note, the old version docs are always left online (in addition to being included with the software download) at their version number link if needed.  For example:  http://ccl.northwestern.edu/netlogo/6.0.4/docs/
