### ISSUE TITLE
bug?: `run` and `runresult` allow `task` primitive to be omitted

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#387]
Uri discovered that NetLogo 5 lets you omit `task` when using `run` or `runresult`:

```
observer> run [ crt 5 ]
observer> print runresult [count turtles]
5
```

It kind of looks like you're running a list, but you aren't; unlike traditional Logos including Berkeley Logo, NetLogo doesn't have symbols, so these can't be lists.  They are tasks, and it works because the compiler takes it to mean:

```
observer> run task [ crt 5 ]
observer> print runresult task [count turtles]
5
```

I was surprised this works.  Having reviewed the relevant code, I think it was actually unintentional that we allow this.  There's a check in `ExpressionParser.parseDelayedBlock` that allows you to omit `task` when using `foreach` and `map` and friends, but that check is written broadly enough that `run` and `runresult` get included too.

The checks can be made more stringent, as follows:

```
--- a/src/main/org/nlogo/parse/ExpressionParser.scala
+++ b/src/main/org/nlogo/parse/ExpressionParser.scala
@@ -520,7 +520,8 @@ class ExpressionParser(
       tokens.next()
       new CommandBlock(stmts, openBracket.start, token.end, token.filename)
     }
-    else if(compatible(goalType, Syntax.ReporterTaskType) &&
+    else if((goalType == Syntax.ReporterTaskType ||
+             goalType == (Syntax.CommandTaskType | Syntax.ReporterTaskType)) &&
             !block.isCommandTask &&
             !compatible(goalType, Syntax.ListType)) {
       val openBracket = tokens.next()
@@ -536,7 +537,8 @@ class ExpressionParser(
       app.addArgument(expr)
       app
     }
-    else if(compatible(goalType, Syntax.CommandTaskType) &&
+    else if((goalType == Syntax.CommandTaskType ||
+             goalType == (Syntax.CommandTaskType | Syntax.ReporterTaskType)) &&
             block.isCommandTask &&
             !compatible(goalType, Syntax.ListType)) {
       val openBracket = tokens.next()
```

With this change all of our automated tests can still be easily made to pass. We have tests like `runresult [5] => 5` and `(runresult [?] 5 6 7 8)` that don't use `task`, but they're just tests of the `run` and `runresult` primitives themselves, not code that actually use them to do anything.

The question remains, is it a bug or a feature?

Allowing `task` to be omitted in this case isn't actually useful, since there's no practical reason to write `run [x]` or `runresult [x]` when you could simply write `x`. So if the programmer writes this, they're almost certainly making a mistake. That argues for disallowing it.

But you can argue for allowing it in the name of simplicity and consistency. If `task` can be omitted when a task is expected, what grounds do we have for forbidding it in this case? We want NetLogo's syntax to be as simple and regular as possible, and plugging this hole requires a more elaborate syntax rule than leaving it open.

**Comment by mrerrormessage** [comment]
Not relevant in the 6.0 beta and later. We've opted to allow the omission of argument list and `->` when an anonymous procedure has no arguments in order to support behavior as listed in this ticket. This also allows anonymous procedures to function more or less as no-context blocks, which can be nice when teaching about them as well (@qiemem has been a big proponent of thinking about anonymous procedures as "block with arguments and no context" and can probably go into greater detail).

**Comment by mrerrormessage** [comment]
Not relevant in the 6.0 beta and later. We've opted to allow the omission of argument list and `->` when an anonymous procedure has no arguments in order to support behavior as listed in this ticket. This also allows anonymous procedures to function more or less as no-context blocks, which can be nice when teaching about them as well (@qiemem has been a big proponent of thinking about anonymous procedures as "block with arguments and no context" and can probably go into greater detail).
