### ISSUE TITLE
User Manual should be in Markdown, not HTML

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#616]
the HTML is hard to hand-maintain

one section of the User Manual is already in Markdown, and the build has support for doing the HTML conversion, so it would just need to be extended to other sections. it could happen a section at a time if redoing the whole manual at once is too daunting

`pandoc` is pretty good at converting markup formats. with a little luck, the results would only need minor manual cleanup

**Comment by frankduncan** [comment]
A first step of this is at e1d22a9

**Comment by Idloj** [comment]
What about using html5 instead of 4?

**Comment by SethTisue** [comment]
What would the advantage be of using HTML5?

If we did any fancy HTML5-specific stuff, we'd need to be sure that it didn't confuse `htmldoc`, which is the tool we use to generate the PDF version of the doc. (It's possible we could or should be using something else; the choice of `htmldoc` was now made more than a decade ago.)

**Comment by Idloj** [comment]
html5 is better designed, friendlier to accessibility software, and is just latest-and-greatest

**Comment by Idloj** [comment]
I can't give classes to paragraphs in Markdown (I don't want raw HTML in my beautiful Markdown).

**Comment by SethTisue** [comment]
see e.g. https://github.com/michelf/php-markdown/issues/157 for some discussion on this. there may be more/better links out there, but this is one I found. one individual asserts, "The reason Markdown allows HTML is so you can do everything you can do with HTML without having to reinvent a syntax for every HTML feature. It's perfectly fine to use HTML within Markdown".

but in any case, yeah, we'd have to figure out something.

**Comment by Idloj** [comment]
Can you write the appropriate pattern/command to give to `sed`?
It should match any paragraph with the following regex above the paragraph(no space between the regex and the paragraph): \{\.\w\} and replace the regex with a `<p class="">` with the class mentioned and a closing tag after the paragraph(there is a blank line before and after the paragraph).

Example:
````

{.bookquote}
*An unspeakable horror seized me. There was a darkness; then a dizzy, sickening 
sensation of sight that was not like seeing; I saw a Line that was no Line; 
Space that was not Space: I was myself, and not myself. When I could find voice, 
I shrieked loud in agony, "Either this is madness or it is Hell."*

````
would convert to:
````

<p class="bookquote">
*An unspeakable horror seized me. There was a darkness; then a dizzy, sickening 
sensation of sight that was not like seeing; I saw a Line that was no Line; 
Space that was not Space: I was myself, and not myself. When I could find voice, 
I shrieked loud in agony, "Either this is madness or it is Hell."*
</p>

````

**Comment by Idloj** [comment]
@frankduncan, I didn't understand 285813afb8ea3fa8d52d9be880036d91d1041823

**Comment by frankduncan** [comment]
That's a script that converts html in the docs section to a pdf that's distributed with NetLogo.  The script was broken for these generated html files, though that will be fixed soon.

**Comment by Idloj** [comment]
What do you mean? pandoc generates those files, doesn't it?

**Comment by frankduncan** [comment]
Nah, htmldoc does

**Comment by Idloj** [comment]
I mean, the csv.html and nw.html (in the release.sh)

**Comment by frankduncan** [comment]
At this point, I'm confused.  htmldoc takes html files (some of which are generated by pandoc from markdown) and puts them together into a pdf.

**Comment by Idloj** [comment]
OK, so what's broken there?

**Comment by frankduncan** [comment]
Nothing anymore after pull #702

**Comment by Idloj** [comment]
@frankduncan, How do files get to docs/dict/ ?

**Comment by frankduncan** [comment]
Apparently through a script that's not getting run.  I'll actually update that for this release.

**Comment by Idloj** [comment]
Found it, there is the py script `bin/dictsplit.py`, seems that it should be run manually. Not nice.
Should we add it to the build process?

This also relates to #634, because the script produces the missing file.
Therefore, I close #634.

**Comment by SethTisue** [comment]
It is already part of the build process if you run `./sbt all`, which is the recommended command for building everything.

**Comment by Idloj** [comment]
Pandoc can also convert HTML to PDF

**Comment by mrerrormessage** [comment]
We've moved closer to this in NetLogo 6:

* Extension documentation is generated from a `documentation.conf` in each extension's root. This allows us to standardize documentation between extensions.
* As part of generating extension documentation in the build, we've introduced `Pegdown` into the build toolset.
* NetLogo 5.3.1 and later use `wkhtmltopdf` instead of `htmldoc` to generate the PDF user manual. `wkhtmltopdf` does much better with modern html than `htmldoc`. With that in mind, we likely *could* move to HTML5, even if that's via markdown.

One big obstacle that remains is that Pegdown doesn't generate anchors for headers (GitHub does). Within the manual, there's a tremendous amount of linking between sections using `page.html#section`. We'd have to be sure that we were properly generating the section IDs (we could add anchors to the markdown manually, render the Pegdown AST ourselves instead of using the default pegdown renderer, or post-process the generated html with some xslt) *and* we that links referring to section IDs were updated to use the appropriate section name.

**Comment by Idloj** [comment]
I found the EXTANCHORLINKS flag on https://github.com/sirthias/pegdown, isn't it what we need?

**Comment by Idloj** [comment]
@mrerrormessage I started working on this. I'm holding it for now until #1347 gets merged, because I plan to add some "special" features (mainly, I want to use `[[wiki-links]]` for prims that will render as links to the dictionary) and there is no point in doing it in pegdown now that we get rid of it.

Just wanted to let you know, so there's no duplicated effort on your side.

**Comment by mrerrormessage** [comment]
@Idloj , please discuss this with me before continuing work. I'm not confident that we actually want to do this for every manual page. Markdown would be great for a lot of pages, but there are many pages where we would have to resort to HTML frequently enough that it may not be worth converting. For example, the dictionary markup is used to split the dictionary out into prim-specific files and I don't see a good way of replicating this in markdown without just writing HTML.

**Comment by Idloj** [comment]
Yeah, I've not converted every page (examples: dictionary, headings), but almost all of them were appropriate for converting.

As for the dictionary, I think maybe we can generate it from a structure similar to that of extensions' `documentation.conf`, what do you think?

**Comment by mrerrormessage** [comment]
OK, if general conversion is working fine, that's great! The dictionary can stay as it is for now; we're working on a project internally to make some major changes to the dictionary, so it will likely completely change within the next year or so.
