### ISSUE TITLE
Strip trailing whitespace when saving a model?

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#725]
This is admittedly a very minor annoyance, but probably a fairly low hanging fruit as well.

Many model authors are not especially careful with trailing whitespace (in both the code and the info tab). When using version control, whitespace additions/deletions show up everywhere in the diffs. Stripping it automatically would make nicer commits in the future.

**Comment by SethTisue** [comment]
Careful though, Markdown (sadly) assigns significance to trailing whitespace in the Info tab.

**Comment by nicolaspayette** [comment]
From http://daringfireball.net/projects/markdown/syntax:

> When you do want to insert a <br /> break tag using Markdown, you end a line with two or more spaces, then type return.

This is... I have no words...

**Comment by nicolaspayette** [comment]
I suppose we could do it for the code but not the info tab? But this makes the fruit a little bit higher and somewhat less juicy... :(

**Comment by qiemem** [comment]
It seems like our parser doesn't actually concatenate lines the markdown typically does:

![image](https://cloud.githubusercontent.com/assets/28215/6491149/e33f9042-c270-11e4-930c-f479a0c41429.png)
![image](https://cloud.githubusercontent.com/assets/28215/6491153/ea71dc26-c270-11e4-8d91-d6e19ba74282.png)

While possibly a bug, this means that the two spaces thing doesn't actually make a difference for us.

Also, I had no idea that two spaces thing existed. What a tragic blemish in an otherwise decent markup language.

If we want to "fix" the concatenation thing, we could enforce the use of `<br/>` for line breaks in model checkout and then we could just strip extra whitespace.

**Comment by nicolaspayette** [comment]
> we could enforce the use of <br/> for line breaks in model checkout

_We_ could (line breaks, as opposed to actual paragraphs, are probably best avoided in info tabs anyway...) but it's possible that non-CCL model authors actually rely on the current behavior...

**Comment by qiemem** [comment]
I confess I misread this issue, thinking it was to add something to models library build process.

That said, we're already messing up line breaks :D

**Comment by SethTisue** [comment]
oh, I forgot that InfoFormatter.scala uses Extensions.HARDWRAPS. ok, so it's fine, we *can* strip trailing whitespace. I think if you look in the models repo you will find old commits from me where I did that to the models en masse, actually.
