### ISSUE TITLE
Return to "Open" dialog after "No Such File or Directory" error pop-up?

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#726]
One more in the "Nicolas reports small annoyances" series:

When opening models, I often type path names directly in the dialog box instead of navigating the folder structure with the mouse. But if I make a small typo in the path, I get the error pop-up and the "Open" dialog is closed, causing me to loose what I typed. It would be nice if, in this case, the user was taken back to the Open dialog, with the previous input available for correction.

**Comment by askadi** [comment]
I believe this is relatively simple. @mrerrormessage 
Store the path name entered before check for valid/invalid path.
If invalid when popup closes force an mouse click event on "open/browse" button and populate the field with the path stored. 

If you could assist me with find the code base for this, it would be great. 

Thanks,
Aditya

**Comment by SethTisue** [comment]
does the error popup include a stack trace? if so, that should take you directly to the relevant code

**Comment by mrerrormessage** [comment]
Hi @askadi , thanks for asking about this PR, but we already have an open PR for it on linux - #956 . It might be helpful to keep an eye on that, perhaps you could implement this feature in Windows or Mac?

**Comment by mrerrormessage** [comment]
Now that #956 has been merged, I think this enhancement is only needed for Windows as I don't think Mac allows you to input a raw filename.

**Comment by askadi** [comment]
Alrighty, I was having a nice look at  NetLogo/src/main/org/nlogo/swing/FileDialog.java.
Now, for Linux its fixed. I would look for a solution to fix issue on windows. 

Thanks!

**Comment by askadi** [comment]
@mrerrormessage I would want to clear couple of things.
* As mentioned in the issue you would want previous input to be there for correction, does it mean once the Error popup is closed you would want to open the file again? Which i believe is correct, because user would know that there is mistake and he needs to correct it.
 Or(As implemented in the PR for linux - #956) you don't want the pop up, but File dialog would reopen again ?
Implementing former case involves lot of analysis, which I am looking into, because filepath from FileDialog goes back to FileMenu.java->FileIO.scala and throws exception thru file2String. So far I believe this is correct.

Alternatively,
We can use JOptionPane for error popup with FileDialog.java, when file does not exist and return to FileDialog once popup is closed with the file path previously entered (perhaps using override for setFileName in JFileChooser ).

Please let me know your thoughts. Thanks!

**Comment by mrerrormessage** [comment]
I'm not sure I understand the question exactly, but it sounds like you are asking about which of the two following scenarios is better.

### Scenario 1
* User enters an invalid filename
* NetLogo fails to find the file
* NetLogo redisplays the file dialog for the user

### Scenario 2
* User enters an invalid filename
* NetLogo fails to find the file
* NetLogo displays an error popup (option pane)  allowing the user to cancel or "try again"
* If user tries again, NetLogo redisplays the file dialog for the user

Of these two I prefer scenario 1. The option to cancel  is available when the user is in the File Dialog. Again, I'm not entirely sure I understand the question, so please let me know if my answer doesn't make sense

**Comment by askadi** [comment]
Yes, you have got it right! I know i should have put my question in a better way. I have made the changes in FileDialog.java, similar to what was done for Linux part before.
Changes are with Scenario 1, as we discussed. 
Scenario 1

    User enters an invalid filename
    NetLogo fails to find the file
    NetLogo redisplays the file dialog for the user

And, I have created a pull request. Not sure how this pull request works--doing it for first time.:)
My Changes:  Fix for Return to open dialog on error #988 
Please let me know if this is good.

**Comment by mrerrormessage** [comment]
@askadi , thanks, I'll review #988 and comment there if there are any issues.

**Comment by mrerrormessage** [comment]
Fixed in #988 (Windows) and #956 (Linux)
