### ISSUE TITLE
`*-link-neighbor?` primitives wrong for undirected link breeds

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#740]
To reproduce:

```
undirected-link-breed [ undirected-links undirected-link ]

to test
  ca
  crt 2
  ask turtle 0 [
    create-undirected-link-with turtle 1
    print link-neighbor? turtle 1
    print out-link-neighbor? turtle 1
    print in-link-neighbor? turtle 1
  ]
end
```

When run, this print:

```
true
true
false
```

But it should print

```
true
false
false
```

The docs do indeed specify that `in-link-neighbor?` and `out-link-neighbor?` only return true for directed links.

**Comment by qiemem** [comment]
`*-link-neighbor? foo` should be equivalent to `member? foo *-link-neighbors`.

**Comment by frankduncan** [comment]
So, some confusion on what should be the expected functionality.  The docs say

"Reports true if there is a directed link going from turtle to the caller."

I can read this one of two ways.  One, return true iff there is a directed link going from caller to callee, false otherwise.  Two, return true if there is a directed link going from caller to callee, with the assumption that you are in a directed links model.

The difference is whether we throw an error in the case of a directed link primitive being used on a situation with undirected links (as we do elsewhere in netlogo).  I'm going to update the docs either way we decide, but I don't know what will be better for modelers.  I'm thinking that we should throw an exception since I can't think of a time when you're using undirected links in your model, but want to use directed link primitives.

@SethTisue @UriCCL please weigh in.

**Comment by qiemem** [comment]
`link-neighbor?` errors in the analogous case (the analagous case being the model is not using breeded links and the default breed is directed).

Furthermore, it seems like `*-link-neighbor? foo` should be exactly the same as `member? foo *-link-neighbors`, which also errors (with "LINKS is an undirected breed.")

**Comment by qiemem** [comment]
Further clarification:

This bug is about the situation in which you're using link breeds. In that situation, you can't have "directed links model" (since you can have both directed and undirected in the same model with breeds). So, it should never error.

The only time an error makes sense is if you're not using link breeds, but are using undirected links.

**Comment by frankduncan** [comment]
Hmm, I see.  So then, should directed links of a directed breed even be considered?  Or put differently, should generic link reporters work on breeded links?

**Comment by frankduncan** [comment]
Based on conversation in hipchat, all directed links, breeded or no, should be considered for out-link-neighbor and in-link-neighbor

**Comment by qiemem** [comment]
Correct. Again, they should be identical to `member? foo *-link-neighbors`. `*-link-neighbors` will include breeded links if you're in a breeded links model.

**Comment by frankduncan** [comment]
This fix is non trivial, based on how the LinkManager reuses findLinkFrom in findLinkEitherWay and how that code propegates to other cases in general.

One possibility is to check the directionality of the returned link, but that's not a good solution, since if you have both an undirected general link and a breeded directed link, and the undirected general link gets returned, it would be false when it should be true.

Another is to cull undirected links out of findLinkFrom based on an input parameter of who is calling it.  But then we have to do a code audit of everyone using the LinkManager to make sure they are using it correctly and add tests, or models may start to fail in odd ways.

I think we should punt on this one for 5.2

**Comment by SethTisue** [comment]
see also #639 which seems very similar
