### ISSUE TITLE
`other` can be used in an observer context

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#757]
It just doesn't do anything. This should probably be a compile-time error, similar to trying to use `pcolor` in an observer context.

**Comment by mrerrormessage** [comment]
This should just be a matter of changing the Agent Class String.

**Comment by SethTisue** [comment]
I don't remember, but this _might_ have been intentional as a way of making it possible to write code that works regardless of the calling agent type? Might be worth considering before simply changing it. After all, the observer is an agent too (on Mondays, Thursdays, and alternate Saturdays, anyway).

**Comment by qiemem** [comment]
Wow, I have no recollection of submitting this issue. In general, I think we should be moving towards treating the observer as just any other agent, not away. When you, for instance, use `other patches` in a turtle context, it behaves the same. That situation seems analogous, and it's behavior correct, so I think this can be closed without "fix".

**Comment by mrerrormessage** [comment]
OK, I'm fine with that. Closing.
