### ISSUE TITLE
error in opening user manual

### ISSUE THREAD

**Issue by jingsam** [NetLogo/NetLogo#840]
When I open user manual in windows 10, it opens 4 tabs in my browser. 
'''
file:///D:/Program
files/
%28x86%29/NetLogo
5.2.0.0/
'''
It seems that netlogo does not handle space properly in the path "D:/Program Files (x86)/NetLogo 5.2.0/docs/index.html"

**Comment by mrerrormessage** [comment]
I just tested this with NetLogo 5.3 and could not replicate. My guess is that this was due to an older JRE (Java 6). NetLogo 5.3 upgrades the JRE to Java 8.

If you are still seeing the problem with 5.3, please comment and we will see about reopening this ticket. My environment:

* 64-bit windows 10
* 64-bit NetLogo 5.3
* Default browser: Microsoft Edge (also tested with Firefox)
* NetLogo installed to C drive
