### ISSUE TITLE
how to change variable precision

### ISSUE THREAD

**Issue by lethphd** [NetLogo/NetLogo#904]
Hi there, 
Is there anyone know how to change variable precision? It is said all the variables are doubles. Is there any way to change that?
Thanks

**Comment by mrerrormessage** [comment]
Numeric variable precision is fixed to the precision of doubles, details of which are available on [this page](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html). All numeric variables are implemented as doubles.

Depending on your purposes in changing the precision, there are a few ways you could go about working around the precision limitations of doubles:

* If you would like to round doubles to a fixed number of decimal places, you can use the [`precision` primitive](http://ccl.northwestern.edu/netlogo/docs/dictionary.html#precision)
* If you would like to carry out precise arithmetic in a particular place, you could write an extension in Java or Scala which accepts two doubles, converts them to `BigDecimal`s, performs the arithmetic and returns the value as a double. This may be ideal for some cases involving very large / very small numbers where the end result will be a number that is well-represented by a double.
* If you would like `BigDecimal` levels of precision everywhere, you could extend the above example to return and generate `BigDecimal` values as `ExtensionObject`s. This is what the `array` and `matrix` extensions do. Unfortunately, these objects wouldn't be able to interact with the numerical parts of NetLogo, they could only be operated on by your extension primitives.

I hope that helps! I'm going to close this issue because it doesn't seem like there's a bug that you're reporting, but please feel free to continue commenting if you have further questions.
