### ISSUE TITLE
version 5.3 will not register as default "opens with"

### ISSUE THREAD

**Issue by lethphd** [NetLogo/NetLogo#906]
I tried to install 5.3 and found it will not register as default "opens with". This will cause "There is no NetLogo reference stored under the name _nl.intern_." problem when using RNetLogo.

Thanks for the great work

**Comment by mrerrormessage** [comment]
I assume you're using NetLogo on Windows? I haven't used RNetLogo before, but it looks to be that you *may* be able to fix the problem by initializing RNetLogo with a different NetLogo path.

The example in the RNetLogo project looks like:

```R
path.to.NetLogo <- "C:/Program Files/NetLogo 5.1.0"
NLStart(path.to.NetLogo, gui=TRUE, nl.obj=nl.test1)
```

If you make it look like the following, it should start to work. Please note that you *may* need to use `Program Files (x86)` instead of `Program Files` if you have the 32-bit NetLogo version installed on 64-bit windows.

```R
path.to.NetLogo <- "C:/Program Files/NetLogo 5.3.0/app"
NLStart(path.to.NetLogo, gui=TRUE, nl.obj=nl.test1)
```

I'm going to close this ticket for now, but if you have any additional problems, please feel free to post them here and we will re-open the ticket as needed. Also, if you are a contributor to RNetLogo (or know any), it would be great to discuss how we can update RNetLogo to make it easier to use it with 5.3 and later versions.
