### ISSUE TITLE
Extensions jars kept open after HeadlessWorkspace disposal

### ISSUE THREAD

**Issue by JusteRaimbault** [NetLogo/NetLogo#909]
Using the headless API from a scala application unveils an issue in extensions jars closing after workspace disposal. Using the simple following code
```scala
import org.nlogo.headless.HeadlessWorkspace

object Test extends App {

  def main(file:String) = {
     for(i <- 1 to 1000){
       println("ws instance "+i.toString)
       open(file)
     }
  }


  def open(file:String) = {
     val ws =  HeadlessWorkspace.newInstance
     ws.open(file)
     Thread.sleep(2000)
     ws.dispose()
  }

  main(args(0))

}
```

that repeats the opening of a NetLogo model and its closing it by disposing of the workspace, one can monitor open files and obtain the following graph :

![openjars](https://cloud.githubusercontent.com/assets/3902759/12122700/edc5980a-b3dc-11e5-80ff-a688ac69ff42.png)

when the model includes an extension, here `extensions [nw]`  (without extensions the issue does not raise). In the graph above, `nw.jar` is monitored ; as a new model is opened each 2 seconds, it seems to appear that the HeadlessWorkspace.dispose() method does not close the jar, which are then closed at garbage collecting (thus the regular spikes).

In the case of a light use, the issue can be ignored, but when running large scale experiments (10^7 runs) with OpenMole it becomes a blocking issue as the maximal number of open files is reached quickly what makes the jvm fail.

Source code for reproducibility (run with `sbt "run $MODEL_PATH"`) : 
[bugnetlogo.zip](https://github.com/NetLogo/NetLogo/files/78686/bugnetlogo.zip)

**Comment by mrerrormessage** [comment]
The `nw` extension in particular uses a lot of jars. Unfortunately, it isn't possible to control exactly when Java unloads jars. Having said that, there are a few ideas that might help:

1) You can call `System.gc()` after calling `workspace.dispose()`. This should encourage java to perform a garbage collection, which will likely also close many of the open files.

2) You can change the operating system limit on the number of open files per process. [This stackoverflow question](http://stackoverflow.com/questions/34588/how-do-i-change-the-number-of-open-files-limit-in-linux) has some great answers about how to do this on different operating systems. This should allow the java process to have additional files open so that it won't run out of space while waiting for a GC.

I'm closing this issue, but please feel free to comment on it if you don't have any success with the above ideas and we'll see whether there's anything more we can do.

**Comment by romainreuillon** [comment]
I am jupping in :)

How does NetLogo load the extension? Does it use an URLClassloader?

I submitted a [PR](https://github.com/NetLogo/NetLogo/pull/908) to solve this issue but from what I tested it doesn't seem to work. I am willing to investigate this issue further since it is a big problem for OpenMOLE users. Do you have any idea where I should look?

@JusteRaimbault could you try it with the patch above? (Sadly, I suspect that you should get the same behaviour)

**Comment by mrerrormessage** [comment]
Ah - I hadn't seen #908 yet. I think that PR can be accepted and it may help to fix the issue we're seeing here. I think it still may be necessary to take one or both of the steps I listed above to actually resolve the issue. 

If the models you are seeing this issue on use any of the `load-` or `save-` functions in nw, the nw extension may have spawned threads which would hold onto loaded classes even after `workspace.dispose()`. This is due to [a bug in gephi](https://github.com/gephi/gephi/issues/854), which we use to save and load various graph formats. If you are using either of these functions, anything else you do may let the model run for a bit longer, but won't let it run indefinitely, as it creates three new threads (each holding onto about a dozen jars) each time the workspace reloads.

**Comment by mrerrormessage** [comment]
Just curious, does this only occur when using the `nw` extension? Does it only occur on 5.3? I'm trying to determine whether this is a bug in 5.3, or whether this has been an ongoing problem.

**Comment by JusteRaimbault** [comment]
It occurs with other extensions as well, and just opening the model is enough to have the issue. I'm experiencing it with 5.3 ; will try with older releases.

**Comment by JusteRaimbault** [comment]
Same issue with NetLogo 5.2 (took the release at [this commit](https://github.com/NetLogo/NetLogo/commit/1e9d34ddcc0ba62fcd8d9813236ecf3205bbf5f8) )
