### ISSUE TITLE
NetLogo pointing to extensions disrupted

### ISSUE THREAD

**Issue by jbadham** [NetLogo/NetLogo#919]
Not sure if it's a NetLogo problem or a problem with the R extension. With Windows (7 and 8.1 at least) and NetLogo 5.3, the following code runs perfectly. Any other code (including that which relies on extensions) works. However, the first time any editing is done, the parser (green tick) throws an error that it can't find any extensions.

````
extensions [r pathdir]

to setup
  r:clear
  let dir pathdir:get-model
  r:put "newdir" dir
  r:eval "setwd(newdir)"
end
````
I don't think the error is in the `pathdir` extension as the problem does not occur if all the `r` code is deleted (ie simply retrieving the directory).

**Comment by mrerrormessage** [comment]
I just installed the R extension on Windows. I have a few notes that might prove helpful:

* I couldn't get the extension working *at all* after following all the steps carefully, but restarting magically made it work. Your mileage may vary.
* With 5.3, extensions are now in the `app/extensions` folder located under the NetLogo installation.
* The rJava extension is regularly updated on CRAN. You may want to check if you have the latest version (I had success with 0.9.7). One set of directions I read instructed me to pull in some jar files from [this page](http://www.rforge.net/JRI/files/). I *did not* do that, since rJava installed those files for me. If you installed those files yourself, I would recommend deleting them and reinstalling the rJava extension to make sure those files are in sync with the rest of rJava.
* The R extension directs users to set the windows `JAVA_HOME` system environment variable to something like ` C:\Program Files (x86)\NetLogo 5.0.2\jre`. With NetLogo 5.3, that path changed to something like `C:\Program Files\NetLogo 5.3\Java\jre1.8.0_65` (depending on whether it's 64-bit or 32-bit and assuming you installed it to the default directory.
* You may need to restart after changing any environment variable for that change to take effect.

Since I can't reproduce this, I'm going to close this as a bug. I will be sending an email to the owner of the R extension letting him know that his instructions need to be updated. If you have questions, feel free to post to this issue and we can continue the conversation.

**Comment by SethTisue** [comment]
(There are a lot of Stack Overflow questions about this, which usually go unanswered...)

**Comment by jbadham** [comment]
Yes, the R extension is incredibly fiddly to get correctly installed.

I am using rJava 0.9-8. I didn't install any of those extra files (and had not actually seen that instruction).

I have the 64bit Windows NetLogo and R versions installed. My JAVA_HOME is correctly pointing to the appropriate directory, and I adjusted the environment variables for the new directory structure where the instructions were wrong.

My r extension passes all the tests in the instructions (eg being able to generate the normal distribution numbers).

I will do some other testing and see if just using R causes the same problem.

**Comment by jbadham** [comment]
I have done a series of individual command tests to isolate the command that introduces the error and it appears to be connected to changing the working directory of R. For me, the following causes problems:

````
extensions [r]

to testSETWD
  r:eval "setwd(\"C:\")"
end
````

The code runs fine. NetLogo continues to work. However, if I run this then try and edit code, I am unable to syntax check the edits.
